"""Erdos #126, independent-architect arm: audit probes.

Stdlib only. Runtime ~1 min. Writes results.json next to this file.

Conventions. S is a set of primes. A finite set A of distinct positive
integers is *S-valid* when every a+b with a != b in A has all its prime
factors in S. g(k) is the max |A| over all S with |S| = k. g_N(k) is the
same max restricted to A subset of [1, N]: a LOWER bound on g(k).
"""

import json
import os
from itertools import combinations

HERE = os.path.dirname(os.path.abspath(__file__))


def primes_upto(n):
    sieve = bytearray([1]) * (n + 1)
    sieve[0:2] = b"\x00\x00"
    for p in range(2, int(n ** 0.5) + 1):
        if sieve[p]:
            sieve[p * p:: p] = bytearray(len(sieve[p * p:: p]))
    return [i for i in range(n + 1) if sieve[i]]


def is_smooth(n, S):
    for p in S:
        while n % p == 0:
            n //= p
    return n == 1


def max_valid_set(S, N):
    """Exhaustive maximum S-valid subset of [1, N]. Branch and bound."""
    S = tuple(sorted(S))
    cand = [a for a in range(1, N + 1)]
    ok = {}

    def compat(a, b):
        key = (a, b) if a < b else (b, a)
        v = ok.get(key)
        if v is None:
            v = is_smooth(a + b, S)
            ok[key] = v
        return v

    best = []

    def expand(cur, pool):
        nonlocal best
        if len(cur) + len(pool) <= len(best):
            return
        if not pool:
            if len(cur) > len(best):
                best = list(cur)
            return
        for i, a in enumerate(pool):
            if len(cur) + len(pool) - i <= len(best):
                return
            nxt = [b for b in pool[i + 1:] if compat(a, b)]
            expand(cur + [a], nxt)

    expand([], cand)
    return best


def verify(A, S):
    return all(is_smooth(a + b, S) for a, b in combinations(sorted(A), 2))


out = {"probe": "erdos-126 independent architect audit", "checks": {}}
P = primes_upto(200)

# ---------------------------------------------------------------- audit 1
# Reproduce the r_186989 table at reduced N. Prior run reported
# g_N(k) = 2, 4, 5, 6, 8, 10, 11 for k = 1..7 with N up to 2e5.
prior = {1: 2, 2: 4, 3: 5, 4: 6, 5: 8, 6: 10}
rows = []
for k, N in [(1, 400), (2, 400), (3, 400), (4, 300), (5, 250), (6, 200)]:
    S = P[:k]
    A = max_valid_set(S, N)
    assert verify(A, S)
    rows.append({"k": k, "S": S, "N": N, "g_N": len(A), "witness": A,
                 "prior_r_186989": prior[k], "agrees": len(A) == prior[k]})
out["checks"]["audit_table"] = rows

# ---------------------------------------------------------------- audit 2
# r_186989 loose thread 3 claims: "|A| <= p-1 when p not in S", by pigeonhole
# on residues mod p. Test at p = 3 with the prior hunt's own witness.
w = [1, 3, 7, 13]
Sw = (2, 5, 7)
out["checks"]["thread3_refutation"] = {
    "claim": "|A| <= p-1 for a prime p not in S",
    "p": 3,
    "S": list(Sw),
    "A": w,
    "A_is_valid": verify(w, Sw),
    "sums": {f"{a}+{b}": a + b for a, b in combinations(w, 2)},
    "no_sum_divisible_by_3": all((a + b) % 3 for a, b in combinations(w, 2)),
    "claim_bound": 2,
    "observed": len(w),
    "claim_refuted": verify(w, Sw) and len(w) > 2,
}

# Does omitting 3 from S cap growth at all? Exhaustive, small N.
noth3 = []
for S, N in [((2, 5, 7), 300), ((2, 5, 7, 11), 250), ((2, 5, 7, 11, 13), 200),
             ((2, 5, 7, 11, 13, 17), 150)]:
    A = max_valid_set(S, N)
    assert verify(A, S)
    noth3.append({"S": list(S), "N": N, "g_N": len(A), "witness": A})
out["checks"]["S_without_3"] = noth3

# 2 not in S really does cap at 2 (the one true parity statement).
odd_only = []
for S, N in [((3, 5, 7), 400), ((3, 5, 7, 11, 13), 300)]:
    A = max_valid_set(S, N)
    odd_only.append({"S": list(S), "N": N, "g_N": len(A), "witness": A})
out["checks"]["S_without_2"] = odd_only

# ---------------------------------------------------------------- audit 3
# The interval construction: A = {1..m} is S-valid for S = primes <= 2m-1.
# Gives g(k) >= m with k = pi(2m-1) -- a lower bound r_186989 never states.
interval = []
for m in range(2, 41):
    S = [p for p in P if p <= 2 * m - 1]
    assert verify(list(range(1, m + 1)), S)
    interval.append({"m": m, "k": len(S), "g_lower_bound": m})
best_by_k = {}
for r in interval:
    if r["k"] not in best_by_k or r["g_lower_bound"] > best_by_k[r["k"]]:
        best_by_k[r["k"]] = r["g_lower_bound"]
out["checks"]["interval_construction"] = {
    "rows": interval,
    "best_lower_bound_by_k": best_by_k,
    "note": "A={1..m}, S=primes<=2m-1, so g(k) >= m with k=pi(2m-1) ~ 2m/log m",
}

# ---------------------------------------------------------------- audit 4
# The S-unit reduction, checked on a concrete witness: fix a1, a2 in A and
# D = a1 - a2; then for every other c, X = (a1+c)/D and Y = -(a2+c)/D are
# units of the group generated by -1, S and D, and X + Y = 1, injectively
# in c. Verified here as exact rationals.
from fractions import Fraction


def in_group(q, gens):
    """Is the rational q (nonzero) a +-product of powers of gens?"""
    n, d = abs(q.numerator), q.denominator
    for p in gens:
        while n % p == 0:
            n //= p
        while d % p == 0:
            d //= p
    return n == 1 and d == 1


A = [1, 2, 3, 5, 7, 13]
S = (2, 3, 5, 7)
assert verify(A, S)
a1, a2 = A[0], A[1]
D = a1 - a2
gens = set(S) | {p for p in P if D % p == 0 or (-D) % p == 0 and p <= abs(D)}
gens = sorted(gens)
sols = []
for c in A:
    if c in (a1, a2):
        continue
    X = Fraction(a1 + c, D)
    Y = Fraction(-(a2 + c), D)
    sols.append({"c": c, "X": str(X), "Y": str(Y), "sums_to_one": X + Y == 1,
                 "X_in_group": in_group(X, gens), "Y_in_group": in_group(Y, gens)})
out["checks"]["unit_equation_reduction"] = {
    "A": A, "S": list(S), "a1": a1, "a2": a2, "D": D, "group_generators": gens,
    "rank_bound": len(gens),
    "solutions": sols,
    "all_valid": all(s["sums_to_one"] and s["X_in_group"] and s["Y_in_group"]
                     for s in sols),
    "distinct_X": len({s["X"] for s in sols}) == len(sols),
}

# ---------------------------------------------------------------- audit 5
# gcd normalisation: gcd(A) divides every pairwise sum, hence is S-smooth,
# hence A/gcd(A) is S-valid. Checked on the witnesses found above.
gcds = []
for r in rows:
    A = r["witness"]
    from math import gcd
    d = 0
    for a in A:
        d = gcd(d, a)
    gcds.append({"k": r["k"], "gcd": d, "gcd_is_smooth": is_smooth(d, r["S"])})
out["checks"]["gcd_normalisation"] = gcds

# ---------------------------------------------------------------- verdict
out["findings"] = [
    {
        "id": "F1",
        "kind": "reduction",
        "claim": "g(k) <= 2 + N(k+1), where N(r) is the maximum number of "
                 "solutions of x+y=1 with x,y in a rank-r subgroup of Q^*. "
                 "Unconditionally g(k) <= 2 + 2^{8k+16} via Beukers-Schlickewei.",
        "status": "proved (elementary, given the cited counting theorem); not new",
        "consequence": "N(r) = exp(o(r)) implies Erdos #126.",
        "direction_check": "one-way: a LOWER bound on N (Erdos-Stewart-Tijdeman) "
                           "does not refute #126.",
    },
    {
        "id": "F2",
        "kind": "audit-refutation",
        "claim": "r_186989 loose thread 3 ('|A| <= p-1 when p not in S') is false.",
        "witness": {"A": w, "S": list(Sw), "p": 3},
        "status": "refuted by explicit witness, verified above",
    },
    {
        "id": "F3",
        "kind": "audit-gap",
        "claim": "r_186989 reports no lower-bound construction; A={1..m} with "
                 "S = primes <= 2m-1 gives g(k) >= (1+o(1)) k log k / 2, which "
                 "already exceeds its largest measured value for k >= 8.",
        "status": "proved (elementary), verified above",
    },
    {
        "id": "F4",
        "kind": "literature",
        "claim": "the best known upper bound is g(k) <= 2^k (Erdos-Suranyi), "
                 "not the 3*2^{k-1} the brief and r_186989 both quote.",
        "status": "secondary source (arXiv:2602.07545 and search summaries); "
                  "not verified against the book in this run",
    },
]

with open(os.path.join(HERE, "results.json"), "w") as fh:
    json.dump(out, fh, indent=2)
print(json.dumps({k: (v if not isinstance(v, list) else f"{len(v)} rows")
                  for k, v in out["checks"].items()}, indent=2)[:2000])
for r in rows:
    print("k=%d N=%d g_N=%d prior=%d agrees=%s %s"
          % (r["k"], r["N"], r["g_N"], r["prior_r_186989"], r["agrees"], r["witness"]))
for r in noth3:
    print("no-3 S=%s N=%d g_N=%d %s" % (r["S"], r["N"], r["g_N"], r["witness"]))
for r in odd_only:
    print("no-2 S=%s g_N=%d %s" % (r["S"], r["g_N"], r["witness"]))
print("interval best by k:", best_by_k)
print("unit reduction all_valid:", out["checks"]["unit_equation_reduction"]["all_valid"],
      "distinct:", out["checks"]["unit_equation_reduction"]["distinct_X"])
