"""WP6, the bonus witness hunt: look for an explicit zero of the prime zeta
function P(s) = sum_p p^(-s) with Re s in (x_star, sigma_c) ~ (1.7287, 1.7795),
along the line sigma_1 = 7/4. Budget capped; the pre-registered prediction P4
expects absence below t = 10^8, and absence changes nothing.

Run from the repo root:

    .venv/bin/python hunts/prime_zeta_rightmost/witness.py

Writes witness_results.json next to this file. Vocabulary contract: decided
means an interval or ball enclosure whose exact endpoints settle a sign,
stated with backend and precision; measured means a float route; heuristic
means an order-of-magnitude model with measured inputs, and is never more
than that. Only the box counter at the bottom can decide a witness, and it
only runs if the screen produces a candidate.

Stage 1, margin analysis (decided, flint 350 bits, iv cross-check).
  At s = sigma_1 + i t the p = 2 term has modulus r_2 = 2^(-sigma_1) and the
  rest of the series has total modulus R = P(sigma_1) - r_2. A zero needs the
  p >= 3 part to land exactly on -2^(-s), so its resultant must shrink from
  the fully aligned maximum R down to r_2. The coherence budget is

      eps_0 = R - r_2 = h(sigma_1) = P(sigma_1) - 2^(1 - sigma_1),

  the same h whose root is sigma_c. With head cutoff X = 50 and prime tail
  T_X = sum_{p > X} p^(-sigma_1), the head budget is identical:
  (head max) - (r_2 - T_X) = (R - T_X) - r_2 + T_X = eps_0 exactly.

Stage 2, required alignment quality and expected t (heuristic).
  Write the loss of the p-term at phase deviation phi_p from perfect
  alignment as l_p = m_p (1 - cos phi_p), m_p = p^(-sigma_1). A zero on the
  line needs total loss exactly eps_0; anywhere in the strip up to sigma_c it
  needs loss <= eps_0 (extra alignment moves the balancing sigma to the
  right, up to sigma_c). Three estimates of the density of such t, using
  Weyl equidistribution of (t log p / 2pi mod 1) on the torus (the log p are
  linearly independent over Q):

  a. Kronecker product of windows. Each single prime must individually obey
     m_p (1 - cos phi_p) <= eps_0, a necessary condition giving a window
     |phi_p| <= arccos(1 - eps_0 / m_p) when eps_0 < 2 m_p. The product of
     window fractions is an upper bound for the density of coherent t (the
     conditions are jointly necessary and the phases are equidistributed
     jointly), hence a lower bound for the expected first t. The equal-share
     variant splits the budget evenly over the constrained primes, which
     maximizes the product of window widths under sum of budgets = eps_0,
     and serves as an optimistic point estimate that ignores every prime
     outside the constrained set.
  b. Chernoff bound. E[exp(-theta l_p)] = exp(-theta m_p) I0(theta m_p)
     = i0e(theta m_p), so Prob(L <= eps) <= exp(theta eps) prod_p
     i0e(theta m_p) for every theta > 0; minimized near the theta that makes
     the tilted mean equal eps. Deterministic, and an upper bound within the
     equidistribution model.
  c. Tilted Monte Carlo. Under exponential tilting the phase of the p-term
     is von Mises with concentration kappa_p = theta m_p, so sampling
     phi_p ~ VonMises(0, kappa_p) and weighting by
     M(theta) exp(theta L) 1{L <= eps}, with M(theta) = prod_p i0e(kappa_p),
     gives an unbiased estimate of Prob(L <= eps). The sampler is checked
     against plain uniform Monte Carlo at a relaxed budget where plain MC
     can see the event.

  The loss model uses the odd primes p <= 1000; the primes beyond 1000 carry
  total modulus tail_1000, so the model brackets the truth between budget
  eps_0 (those primes maximally helpful) and eps_0 - 2 tail_1000 (maximally
  hostile). Expected first t: coherent moments arrive with density
  Prob(L <= eps); while coherent, the resultant direction and the target
  direction -arg(2^(-it)) drift at relative angular speed nu_rel =
  |nu_odd - log 2| (nu_odd the modulus-weighted mean of log p over the odd
  head), so zeros arrive at rate about Prob * nu_rel / 2pi per unit t and

      t_expected ~ 2 pi / (nu_rel * Prob(L <= eps)).

  Order of magnitude only: it treats coherence and direction as independent
  and ignores the duration of coherent excursions.

Stage 3, the screen (measured, numpy float64).
  |F(sigma_1 + i t)| for F the head over primes p <= 47, on the uniform grid
  t in [0, 10^8] with step = (2 pi / nu_bar) / 8, where nu_bar is the
  modulus-weighted mean oscillation frequency sum m_p log p / sum m_p (the
  mean oscillation scale of the task brief). Phases are generated by the
  exact-grid recurrence exp(-i (t0 + j dt) log p) =
  exp(-i t0 log p) exp(-i j dt log p), with the per-chunk array reused, and
  spot-checked against direct evaluation. ||P| - |F|| <= T_50 pointwise.
  Refinement pass A re-evaluates the best coarse windows with primes
  <= 10^4, pass B with primes <= 10^6; beyond 10^6 the prime tail is below
  the all-integer bound (10^6)^(-3/4) / (3/4) + (10^6)^(-7/4) < 4.22e-5.
  The line screen is only sensitive to zeros within roughly 0.01 of
  sigma_1 in the real direction (typical |P'| is a few tenths).

Stage 4, candidate gate (runs only if pass B finds |P| < 1e-4).
  Polish by mpmath findroot (muller) on mpmath.primezeta from the best
  point; a polished root counts as a witness only if a small box around it,
  strictly inside (x_star, sigma_c) by exact comparison against the decided
  intervals of decide.py, gets a decided winding number >= 1 from the
  argument-principle counter below.

The box counter (decided when it reports so, python-flint acb).
  P is enclosed on balls by the Moebius series sum_{k<=K} mu(k)/k
  log zeta(k s) plus the tail ball |sum_{k>K}| <= 3 * 2^(-(K+1) sigma_lo)
  / ((K+1)(1 - 2^(-sigma_lo))) with sigma_lo the exact lower endpoint of
  Re s (the bound of instrument.py docstring 1, monotone in sigma). The
  winding number of P - c around a rectangle is the sum of the argument
  increments arg(v_{j+1} / v_j) over a boundary sampling: if every boundary
  ball excludes 0 and every increment enclosure stays strictly inside
  (-pi, pi), the total is 2 pi times the winding number, and the integer is
  decided when the exact-endpoint enclosure of total / 2 pi contains exactly
  one integer. All comparisons are exact rational endpoint comparisons; pi
  enters only through the exact endpoints of the arb.pi ball. Two controls
  run unconditionally: a null box far from any zero (winding 0) and a
  shifted function P - c with a zero planted inside by construction
  (winding 1), so the gated tool is exercised even when no candidate exists.
"""

from __future__ import annotations

import json
import os
import sys
import time
from fractions import Fraction
from math import acos, ceil, cos, floor, log, pi, sqrt

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import flint
import mpmath
import numpy as np
import scipy.special as sp
from mpmath import mp

from instrument import (
    Timer,
    arb_endpoints,
    arb_from_fraction,
    decided_sign,
    iv_endpoints,
    iv_from_fraction,
    mobius_sieve,
    outward_decimal,
    prime_zeta_arb,
    prime_zeta_iv,
)

arb = flint.arb
acb = flint.acb
fctx = flint.ctx
iv = mpmath.iv

HERE = os.path.dirname(os.path.abspath(__file__))

SIGMA1 = Fraction(7, 4)          # exactly representable as a float too
SIGMA1_F = 1.75
X_HEAD = 50                      # head cutoff for margin analysis and screen
T_MAX = 1.0e8                    # screen ceiling (pre-registered in P4)
FLINT_PREC = 350
IV_DPS = 40
K_MOEBIUS = 120                  # flint Moebius series depth (as in decide.py)
K_IV = 40
COH_PRIME_CUTOFF = 1000          # loss-model prime cutoff
IS_SAMPLES_MAIN = 500_000
IS_SAMPLES_SIDE = 200_000
IS_BATCH = 100_000
RNG_SEED = 20260816
CANDIDATE_THRESHOLD = 1e-4       # refined |P| below this triggers the gate
EXPECTED_T_GATE = 1.0e12


def np_primes_upto(n: int) -> np.ndarray:
    sieve = np.ones(n + 1, dtype=bool)
    sieve[:2] = False
    for p in range(2, int(n ** 0.5) + 1):
        if sieve[p]:
            sieve[p * p:: p] = False
    return np.nonzero(sieve)[0]


def fr_from_decimal(s: str) -> Fraction:
    return Fraction(s)


def enclosure_record(lo: Fraction, hi: Fraction, digits: int) -> dict:
    dlo, dhi = outward_decimal(lo, hi, digits)
    return {"interval": [dlo, dhi], "width": f"{float(hi - lo):.3e}"}


# ----------------------------------------------------------------------
# Stage 1: margin analysis, decided
# ----------------------------------------------------------------------

def margin_analysis(mu):
    fctx.prec = FLINT_PREC
    out = {}
    with Timer() as t:
        s = arb_from_fraction(SIGMA1)
        P = prime_zeta_arb(s, K_MOEBIUS, mu)
        r2 = arb(2) ** (-s)
        R = P - r2
        eps0 = R - r2
        head_all = arb(0)
        for p in np_primes_upto(X_HEAD - 1):
            head_all += arb(int(p)) ** (-s)
        T50 = P - head_all
        head_odd = head_all - r2
    P_lo, P_hi = arb_endpoints(P)
    r2_lo, r2_hi = arb_endpoints(r2)
    R_lo, R_hi = arb_endpoints(R)
    e_lo, e_hi = arb_endpoints(eps0)
    T_lo, T_hi = arb_endpoints(T50)
    ho_lo, ho_hi = arb_endpoints(head_odd)
    out["flint"] = {
        "backend": "python-flint (arb)",
        "precision": f"{FLINT_PREC} bits",
        "moebius_K": K_MOEBIUS,
        "time_s": round(t.seconds, 3),
        "P_at_sigma1": enclosure_record(P_lo, P_hi, 33),
        "r2": enclosure_record(r2_lo, r2_hi, 33),
        "R_total_modulus_p_ge_3": enclosure_record(R_lo, R_hi, 33),
        "eps0_budget_R_minus_r2": enclosure_record(e_lo, e_hi, 33),
        "head_odd_modulus_3_to_47": enclosure_record(ho_lo, ho_hi, 33),
        "prime_tail_T50_p_gt_47": enclosure_record(T_lo, T_hi, 33),
        "eps0_positive_decided": decided_sign(e_lo, e_hi) == 1,
        "head_cancellation_feasible": {
            "statement": "head budget (head_odd max) - (r2 - T50) equals eps0 "
                         "exactly by construction, and eps0 > 0 is decided, so "
                         "the p <= 47 head can in principle cancel the p = 2 "
                         "term with best-case tail phase",
            "decided": decided_sign(e_lo, e_hi) == 1,
        },
    }
    # iv cross-check of the central quantity
    iv.dps = IV_DPS
    with Timer() as t:
        s_iv = iv_from_fraction(SIGMA1)
        P_iv = prime_zeta_iv(s_iv, K_IV, mu)
        e_iv = P_iv - iv.mpf(2) ** (1 - s_iv)
    Pi_lo, Pi_hi = iv_endpoints(P_iv)
    ei_lo, ei_hi = iv_endpoints(e_iv)
    out["mpmath_iv"] = {
        "backend": "mpmath.iv",
        "precision": f"dps {IV_DPS}",
        "moebius_K": K_IV,
        "time_s": round(t.seconds, 3),
        "P_at_sigma1": enclosure_record(Pi_lo, Pi_hi, 14),
        "eps0_budget": enclosure_record(ei_lo, ei_hi, 14),
        "eps0_positive_decided": decided_sign(ei_lo, ei_hi) == 1,
    }
    out["cross_checks"] = {
        "P_backends_intersect": max(P_lo, Pi_lo) <= min(P_hi, Pi_hi),
        "P_flint_inside_iv": Pi_lo <= P_lo and P_hi <= Pi_hi,
        "eps0_backends_intersect": max(e_lo, ei_lo) <= min(e_hi, ei_hi),
    }
    floats = {
        "P": float((P_lo + P_hi) / 2),
        "r2": float((r2_lo + r2_hi) / 2),
        "R": float((R_lo + R_hi) / 2),
        "eps0": float((e_lo + e_hi) / 2),
        "T50": float((T_lo + T_hi) / 2),
        "head_odd": float((ho_lo + ho_hi) / 2),
    }
    return out, floats


# ----------------------------------------------------------------------
# Stage 2: alignment quality and expected t, heuristic
# ----------------------------------------------------------------------

def window_products(m_odd_head: np.ndarray, primes_odd_head: np.ndarray, eps0: float):
    rows = []
    full_prod = 1.0
    constrained = []
    for p, m in zip(primes_odd_head, m_odd_head):
        if eps0 < 2 * m:
            th = acos(1 - eps0 / m)
            frac = th / pi
            full_prod *= frac
            constrained.append((int(p), float(m)))
            rows.append({"p": int(p), "m_p": float(m),
                         "theta_max_rad": round(th, 4),
                         "window_fraction": round(frac, 4)})
        else:
            rows.append({"p": int(p), "m_p": float(m),
                         "theta_max_rad": None, "window_fraction": 1.0,
                         "note": "individually unconstrained, eps0 >= 2 m_p"})
    n_c = len(constrained)
    eq_prod = 1.0
    for p, m in constrained:
        arg = 1 - eps0 / (n_c * m)
        th = acos(max(-1.0, arg))
        eq_prod *= th / pi
    return rows, full_prod, eq_prod, n_c


def solve_theta(mvec: np.ndarray, eps: float) -> float:
    def mean_loss(theta):
        k = theta * mvec
        r = np.where(k > 0, sp.i1e(k) / sp.i0e(k), 0.0)
        return float(np.sum(mvec * (1.0 - r)))
    lo, hi = 0.0, 1.0
    while mean_loss(hi) > eps:
        hi *= 2.0
        if hi > 1e12:
            break
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if mean_loss(mid) > eps:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def chernoff_log10(mvec: np.ndarray, eps: float, theta: float) -> float:
    k = theta * mvec
    return (theta * eps + float(np.sum(np.log(sp.i0e(k))))) / log(10.0)


def coherence_prob_tilted(mvec: np.ndarray, eps: float, n_samples: int,
                          rng: np.random.Generator, batch: int = IS_BATCH):
    theta = solve_theta(mvec, eps)
    kap = theta * mvec
    log_m_theta = float(np.sum(np.log(sp.i0e(kap))))
    total_w = 0.0
    total_w2 = 0.0
    n_done = 0
    n_hits = 0
    while n_done < n_samples:
        b = min(batch, n_samples - n_done)
        phi = rng.vonmises(0.0, kap, size=(b, mvec.size))
        L = ((1.0 - np.cos(phi)) * mvec).sum(axis=1)
        w = np.where(L <= eps, np.exp(theta * (L - eps)), 0.0)
        total_w += float(w.sum())
        total_w2 += float((w * w).sum())
        n_hits += int(np.count_nonzero(w))
        n_done += b
    mean_w = total_w / n_done
    var_w = max(0.0, total_w2 / n_done - mean_w ** 2)
    stderr_w = sqrt(var_w / n_done)
    scale = log_m_theta + theta * eps          # log of M(theta) e^{theta eps}
    prob = mean_w * np.exp(scale)
    stderr = stderr_w * np.exp(scale)
    return {
        "prob": float(prob),
        "stderr": float(stderr),
        "theta": float(theta),
        "n_samples": int(n_done),
        "hit_fraction_tilted": n_hits / n_done,
        "chernoff_upper_log10": chernoff_log10(mvec, eps, theta),
    }


def coherence_prob_plain(mvec: np.ndarray, eps: float, n_samples: int,
                         rng: np.random.Generator, batch: int = 200_000):
    hits = 0
    n_done = 0
    while n_done < n_samples:
        b = min(batch, n_samples - n_done)
        phi = rng.uniform(-pi, pi, size=(b, mvec.size))
        L = ((1.0 - np.cos(phi)) * mvec).sum(axis=1)
        hits += int(np.count_nonzero(L <= eps))
        n_done += b
    p = hits / n_done
    return {"prob": p, "stderr": sqrt(max(p * (1 - p), 1e-300) / n_done),
            "n_samples": n_done, "hits": hits}


# ----------------------------------------------------------------------
# Stage 3: the screen
# ----------------------------------------------------------------------

def coarse_screen(primes_head: np.ndarray, step: float):
    logp = np.log(primes_head.astype(float))
    mvec = primes_head.astype(float) ** (-SIGMA1_F)
    n_points = int(floor(T_MAX / step)) + 1
    chunk = 1 << 19
    n_chunks = (n_points + chunk - 1) // chunk
    E = [np.exp(-1j * lp * step * np.arange(chunk)) for lp in logp]
    chunk_min = np.empty(n_chunks)
    chunk_argt = np.empty(n_chunks)
    thresholds = [0.05, 0.02, 0.01, 0.005, 0.002, 0.001]
    counts = {str(th): 0 for th in thresholds}
    gmax_val, gmax_t = -1.0, 0.0
    with Timer() as tm:
        for c in range(n_chunks):
            i0 = c * chunk
            n = min(chunk, n_points - i0)
            t0 = i0 * step
            S = np.zeros(n, dtype=complex)
            for lp, m, Ep in zip(logp, mvec, E):
                S += (m * np.exp(-1j * lp * t0)) * Ep[:n]
            a = np.abs(S)
            j = int(np.argmin(a))
            chunk_min[c] = a[j]
            chunk_argt[c] = t0 + j * step
            for th in thresholds:
                counts[str(th)] += int(np.count_nonzero(a < th))
            if c == 0:
                tloc = np.arange(n) * step
                jmask = (tloc >= 10.0) & (tloc <= 100.0)
                jj = int(np.argmax(np.where(jmask, a, -1.0)))
                gmax_val, gmax_t = float(a[jj]), t0 + jj * step
    # spot-check the phase recurrence against direct evaluation
    rng = np.random.default_rng(7)
    dev = 0.0
    for idx in rng.integers(0, n_points, size=8):
        t = float(idx) * step
        direct = np.abs(np.sum(mvec * np.exp(-1j * t * logp)))
        c, j = int(idx) // chunk, int(idx) % chunk
        t0 = c * chunk * step
        rec = np.abs(sum((m * np.exp(-1j * lp * t0)) * np.exp(-1j * lp * step * j)
                         for lp, m in zip(logp, mvec)))
        dev = max(dev, abs(float(direct) - float(rec)))
    order = np.argsort(chunk_min)
    return {
        "n_points": n_points,
        "n_chunks": n_chunks,
        "chunk": chunk,
        "time_s": round(tm.seconds, 1),
        "counts_below": counts,
        "recurrence_vs_direct_max_dev": float(dev),
        "chunk_min": chunk_min,
        "chunk_argt": chunk_argt,
        "order": order,
        "argmax_for_null_box": {"t": gmax_t, "absF": gmax_val},
    }


def eval_head(ts: np.ndarray, primes: np.ndarray) -> np.ndarray:
    logp = np.log(primes.astype(float))
    mvec = primes.astype(float) ** (-SIGMA1_F)
    S = np.zeros(ts.size, dtype=complex)
    block = 10_000
    for b0 in range(0, primes.size, block):
        lp = logp[b0:b0 + block]
        mm = mvec[b0:b0 + block]
        S += (mm * np.exp(-1j * np.outer(ts, lp))).sum(axis=1)
    return np.abs(S)


def refine(screen, step: float):
    p1e4 = np_primes_upto(10_000)
    p1e6 = np_primes_upto(1_000_000)
    rem6 = (1e6) ** (-0.75) / 0.75 + (1e6) ** (-1.75)
    # pass A: best 40 coarse windows, primes <= 1e4
    top = screen["order"][:40]
    bestA = []
    with Timer() as tA:
        for c in top:
            tc = screen["chunk_argt"][c]
            ts = tc + np.linspace(-step, step, 257)
            ts = ts[ts >= 0]
            a = eval_head(ts, p1e4)
            j = int(np.argmin(a))
            bestA.append((float(a[j]), float(ts[j])))
    bestA.sort()
    # pass B: best 10 refined points, primes <= 1e6
    bestB = []
    with Timer() as tB:
        for val, tc in bestA[:10]:
            ts = tc + np.linspace(-step / 128, step / 128, 257)
            ts = ts[ts >= 0]
            a = eval_head(ts, p1e6)
            j = int(np.argmin(a))
            bestB.append((float(a[j]), float(ts[j])))
    bestB.sort()
    return {
        "passA": {"windows": 40, "primes_upto": 10_000, "n_primes": int(p1e4.size),
                  "grid_halfwidth": step, "grid_points": 257,
                  "time_s": round(tA.seconds, 1),
                  "best10": [{"absP_head": v, "t": t} for v, t in bestA[:10]]},
        "passB": {"windows": 10, "primes_upto": 1_000_000, "n_primes": int(p1e6.size),
                  "grid_halfwidth": step / 128, "grid_points": 257,
                  "time_s": round(tB.seconds, 1),
                  "tail_bound_beyond_1e6": rem6,
                  "tail_bound_note": "all-integer bound (1e6)^(-3/4)/(3/4) + (1e6)^(-7/4), measured floats",
                  "best5": [{"absP_head_1e6": v, "t": t,
                             "absP_interval": [max(0.0, v - rem6), v + rem6]}
                            for v, t in bestB[:5]]},
        "best": {"absP_head_1e6": bestB[0][0], "t": bestB[0][1],
                 "absP_interval": [max(0.0, bestB[0][0] - rem6), bestB[0][0] + rem6]},
    }


# ----------------------------------------------------------------------
# The box counter: argument-principle winding, decided when reported so
# ----------------------------------------------------------------------

def prime_zeta_acb(s: acb, K: int, mu, sigma_lo: Fraction) -> acb:
    """Ball enclosure of P(s) for Re s >= sigma_lo > 1: Moebius series plus
    the tail ball of instrument.py docstring 1 (monotone in sigma, so the
    exact lower endpoint sigma_lo of Re s gives a valid bound)."""
    total = acb(0)
    for k in range(1, K + 1):
        if mu[k] == 0:
            continue
        total += (acb(mu[k]) / k) * (k * s).zeta().log()
    sl = arb_from_fraction(sigma_lo)
    T = 3 * arb(2) ** (-(arb(K + 1) * sl)) / ((K + 1) * (1 - arb(2) ** (-sl)))
    ball = T.union(-T)
    return total + acb(ball, ball)


def winding_count(center: complex, half_w: Fraction, c_shift: acb, K: int, mu,
                  m_per_edge: int = 24, max_refine: int = 3) -> dict:
    """Decided winding number of P(s) - c_shift around the square
    center +/- half_w, or an honest failure record. Exact-rational endpoint
    bookkeeping throughout; pi enters via the exact endpoints of arb.pi()."""
    cx = Fraction(center.real).limit_denominator(10 ** 12)
    cy = Fraction(center.imag).limit_denominator(10 ** 12)
    sigma_lo = cx - half_w
    pi_lo, pi_hi = arb_endpoints(arb.pi())
    for attempt in range(max_refine + 1):
        M = m_per_edge * (2 ** attempt)
        pts = []
        for j in range(M):
            f = Fraction(j, M)
            pts.append((cx - half_w + 2 * half_w * f, cy - half_w))
        for j in range(M):
            f = Fraction(j, M)
            pts.append((cx + half_w, cy - half_w + 2 * half_w * f))
        for j in range(M):
            f = Fraction(j, M)
            pts.append((cx + half_w - 2 * half_w * f, cy + half_w))
        for j in range(M):
            f = Fraction(j, M)
            pts.append((cx - half_w, cy + half_w - 2 * half_w * f))
        vals = []
        ok = True
        for (x, y) in pts:
            v = prime_zeta_acb(acb(arb_from_fraction(x), arb_from_fraction(y)),
                               K, mu, sigma_lo) - c_shift
            if not bool(v.abs_lower() > 0):
                ok = False
                break
            vals.append(v)
        if not ok:
            continue
        tot_lo = Fraction(0)
        tot_hi = Fraction(0)
        ok = True
        for j in range(len(vals)):
            th = (vals[(j + 1) % len(vals)] / vals[j]).arg()
            th_lo, th_hi = arb_endpoints(th)
            if not (-pi_lo < th_lo and th_hi < pi_lo):
                ok = False
                break
            tot_lo += th_lo
            tot_hi += th_hi
        if not ok:
            continue
        cands = [tot_lo / (2 * pi_lo), tot_lo / (2 * pi_hi),
                 tot_hi / (2 * pi_lo), tot_hi / (2 * pi_hi)]
        w_lo, w_hi = min(cands), max(cands)
        n_lo, n_hi = ceil(w_lo), floor(w_hi)
        if n_lo == n_hi:
            return {"decided": True, "winding": int(n_lo),
                    "boundary_points": len(vals), "attempts": attempt + 1}
        return {"decided": False,
                "reason": "winding enclosure contains more than one integer",
                "enclosure": [float(w_lo), float(w_hi)],
                "boundary_points": len(vals)}
    return {"decided": False,
            "reason": "a boundary ball contained 0 or an argument increment "
                      "could not be kept inside (-pi, pi) at the refinement cap"}


def box_counter_controls(screen) -> dict:
    """Exercise the counter unconditionally: a null box (expect winding 0)
    and a planted zero of P - c (expect winding 1)."""
    saved = fctx.prec
    fctx.prec = 192
    K = 25
    mu = mobius_sieve(K + 1)
    out = {"backend": "python-flint (acb)", "precision": "192 bits",
           "moebius_K": K}
    try:
        t_null = screen["argmax_for_null_box"]["t"]
        with Timer() as tm:
            r0 = winding_count(complex(SIGMA1_F, t_null), Fraction(1, 100),
                               acb(0), K, mu)
        out["null_box"] = {
            "center": [SIGMA1_F, t_null], "half_width": "1/100",
            "expected_winding": 0, "result": r0, "time_s": round(tm.seconds, 1),
            "note": "center chosen at the coarse-grid |F| maximum, far from "
                    "any zero of P",
        }
        sc = complex(SIGMA1_F, t_null + 0.5)
        cxy = acb(arb_from_fraction(Fraction(sc.real).limit_denominator(10 ** 12)),
                  arb_from_fraction(Fraction(sc.imag).limit_denominator(10 ** 12)))
        val = prime_zeta_acb(cxy, K, mu, Fraction(sc.real).limit_denominator(10 ** 12) - Fraction(1, 100))
        c_mid = acb(val.real.mid(), val.imag.mid())
        with Timer() as tm:
            r1 = winding_count(sc, Fraction(1, 100), c_mid, K, mu)
        out["planted_zero_box"] = {
            "center": [sc.real, sc.imag], "half_width": "1/100",
            "expected_winding": 1, "result": r1, "time_s": round(tm.seconds, 1),
            "note": "c is the exact dyadic midpoint of the ball P(center), so "
                    "P - c has a zero within the ball radius of the center by "
                    "construction; a decided winding 1 validates the counter",
        }
        out["both_controls_pass"] = bool(
            r0.get("decided") and r0.get("winding") == 0
            and r1.get("decided") and r1.get("winding") == 1)
    finally:
        fctx.prec = saved
    return out


# ----------------------------------------------------------------------
# Stage 4: candidate polish (gated; P4 expects this never to run)
# ----------------------------------------------------------------------

def polish_and_decide(t_best: float, decided_consts: dict) -> dict:
    out = {"ran": True}
    mp.dps = 40
    try:
        s0 = mp.findroot(lambda s: mp.primezeta(s), mp.mpc(SIGMA1_F, t_best),
                         solver="muller", tol=1e-30)
    except Exception as e:  # noqa: BLE001
        out["converged"] = False
        out["error"] = str(e)
        return out
    resid = abs(mp.primezeta(s0))
    out["converged"] = True
    out["s0"] = [mp.nstr(s0.real, 25), mp.nstr(s0.imag, 25)]
    out["residual"] = float(resid)
    out["polish"] = "mpmath findroot (muller) on mpmath.primezeta, dps 40; measured"
    xs_hi = fr_from_decimal(decided_consts["x_star"]["flint"]["interval"][1])
    sc_lo = fr_from_decimal(decided_consts["sigma_c"]["flint"]["interval"][0])
    re0 = Fraction(float(s0.real)).limit_denominator(10 ** 15)
    half_w = Fraction(1, 1000)
    in_window = xs_hi < re0 - half_w and re0 + half_w < sc_lo
    out["box_strictly_inside_window_decided"] = bool(in_window)
    if not in_window or resid > 1e-25:
        out["witness_decided"] = False
        return out
    saved = fctx.prec
    fctx.prec = 256
    K = 40
    mu = mobius_sieve(K + 1)
    try:
        r = winding_count(complex(float(s0.real), float(s0.imag)), half_w,
                          acb(0), K, mu)
    finally:
        fctx.prec = saved
    out["box_count"] = r
    out["witness_decided"] = bool(r.get("decided") and r.get("winding", 0) >= 1)
    return out


# ----------------------------------------------------------------------
# main
# ----------------------------------------------------------------------

def main() -> None:
    t_start = time.perf_counter()
    mu = mobius_sieve(K_MOEBIUS + 1)
    rng = np.random.default_rng(RNG_SEED)

    out: dict = {
        "hunt": "prime_zeta_rightmost",
        "task": "WP6 bonus witness hunt at sigma_1 = 7/4",
        "date": "2026-08-16",
        "versions": {
            "python-flint": getattr(flint, "__version__", "unknown"),
            "mpmath": mpmath.__version__,
            "numpy": np.__version__,
        },
        "vocabulary": "decided = enclosure with exact endpoint sign logic, "
                      "stated with backend and precision; measured = float "
                      "route; heuristic = order-of-magnitude model with "
                      "measured inputs",
        "rng_seed": RNG_SEED,
    }

    # ---------------- stage 1 ----------------
    margin, mf = margin_analysis(mu)
    out["margin_analysis"] = margin
    eps0 = mf["eps0"]
    r2 = mf["r2"]
    R = mf["R"]
    T50 = mf["T50"]

    # ---------------- stage 2 ----------------
    primes_head = np_primes_upto(X_HEAD - 1)
    m_head = primes_head.astype(float) ** (-SIGMA1_F)
    primes_odd_head = primes_head[1:]
    m_odd_head = m_head[1:]

    rows, full_prod, eq_prod, n_c = window_products(m_odd_head, primes_odd_head, eps0)
    delta_rms = sqrt(2 * eps0 / R)

    p_coh = np_primes_upto(COH_PRIME_CUTOFF)
    p_coh_odd = p_coh[1:]
    m_coh = p_coh_odd.astype(float) ** (-SIGMA1_F)
    # measured prime tail beyond the loss-model cutoff
    p_to_1e6 = np_primes_upto(1_000_000)
    tail_1000 = float(np.sum(p_to_1e6[p_to_1e6 > COH_PRIME_CUTOFF].astype(float)
                             ** (-SIGMA1_F))) + (1e6) ** (-0.75) / 0.75

    eps_win_lo = fr_from_decimal(
        json.load(open(os.path.join(HERE, "decided.json")))
        ["decisions"]["margin_P_at_x_star_minus_2_pow_1_minus_x_star_gt_1_over_60"]
        ["flint"]["h_enclosure"][0])
    eps_win = float(eps_win_lo)

    with Timer() as tm:
        is_main = coherence_prob_tilted(m_coh, eps0, IS_SAMPLES_MAIN, rng)
        is_pess = coherence_prob_tilted(m_coh, max(1e-6, eps0 - 2 * tail_1000),
                                        IS_SAMPLES_SIDE, rng)
        is_win = coherence_prob_tilted(m_coh, eps_win, IS_SAMPLES_SIDE, rng)
        eps_test = 0.12
        plain_chk = coherence_prob_plain(m_coh, eps_test, 2_000_000, rng)
        is_chk = coherence_prob_tilted(m_coh, eps_test, 200_000, rng)
    denom = sqrt(plain_chk["stderr"] ** 2 + is_chk["stderr"] ** 2)
    agree_sigmas = abs(plain_chk["prob"] - is_chk["prob"]) / denom if denom > 0 else None

    nu_bar = float(np.sum(m_head * np.log(primes_head)) / np.sum(m_head))
    nu_odd = float(np.sum(m_odd_head * np.log(primes_odd_head)) / np.sum(m_odd_head))
    nu_rel = abs(nu_odd - log(2.0))

    def t_exp(prob):
        return 2 * pi / (nu_rel * prob) if prob > 0 else float("inf")

    t_exp_main = t_exp(is_main["prob"])
    t_exp_pess = t_exp(is_pess["prob"])
    t_exp_win = t_exp(is_win["prob"])

    out["required_alignment"] = {
        "grade": "heuristic (measured float inputs; equidistribution model)",
        "rms_phase_coherence_delta": delta_rms,
        "rms_note": "sqrt(2 eps0 / R): rms phase spread of the p >= 3 terms "
                    "that shrinks the resultant from R to r2 at second order",
        "per_prime_windows_full_budget": rows,
        "n_constrained_primes": n_c,
        "kronecker_window_products": {
            "full_budget_product": full_prod,
            "full_budget_note": "product of individually necessary windows; an "
                                "upper bound for the coherent-t density within "
                                "the model, hence a lower bound on expected t",
            "equal_share_product": eq_prod,
            "equal_share_note": "budget split evenly over the constrained "
                                "primes (maximizes the product); optimistic, "
                                "ignores all smaller primes",
        },
        "coherence_probability": {
            "model": f"loss L = sum m_p (1 - cos phi_p) over odd primes "
                     f"p <= {COH_PRIME_CUTOFF}; Prob(L <= eps) by von Mises "
                     "tilted importance sampling; Chernoff upper bound "
                     "exp(theta eps) prod i0e(theta m_p)",
            "tail_beyond_cutoff": tail_1000,
            "at_eps0_line_budget": is_main,
            "at_eps0_minus_2tail_pessimistic": is_pess,
            "at_window_budget_h_at_x_star": is_win,
            "sampler_check_at_eps_0p12": {
                "plain_mc": plain_chk, "tilted_is": is_chk,
                "difference_in_combined_stderr_units": agree_sigmas,
            },
            "time_s": round(tm.seconds, 1),
        },
    }
    out["expected_t"] = {
        "grade": "heuristic (order of magnitude)",
        "formula": "t_expected ~ 2 pi / (nu_rel * Prob(L <= eps)); zeros "
                   "arrive at rate Prob * nu_rel / 2pi per unit t while the "
                   "resultant direction sweeps the target",
        "nu_bar_weighted_mean_freq": nu_bar,
        "nu_odd": nu_odd,
        "nu_rel": nu_rel,
        "on_line_sigma1_budget_eps0": t_exp_main,
        "pessimistic_budget": t_exp_pess,
        "window_wide_budget_h_at_x_star": t_exp_win,
        "expected_zero_count_below_1e8_line_budget":
            T_MAX * is_main["prob"] * nu_rel / (2 * pi),
        "expected_zero_count_below_1e8_window_budget":
            T_MAX * is_win["prob"] * nu_rel / (2 * pi),
        "beyond_1e12_gate": {
            "gate": EXPECTED_T_GATE,
            "line_estimate_beyond": t_exp_main > EXPECTED_T_GATE,
            "note": "whichever side of 1e12 the point estimate falls, every "
                    "estimate is far beyond the 1e8 screen ceiling, so the "
                    "plan is unchanged: cheap screen, then stop; P4 expects "
                    "absence",
        },
    }

    # ---------------- stage 3 ----------------
    step = (2 * pi / nu_bar) / 8
    screen = coarse_screen(primes_head, step)
    order = screen["order"]
    top10 = [{"absF47": float(screen["chunk_min"][c]),
              "t": float(screen["chunk_argt"][c])} for c in order[:10]]
    gmin = float(screen["chunk_min"][order[0]])
    gmin_t = float(screen["chunk_argt"][order[0]])
    ref = refine(screen, step)
    best = ref["best"]

    out["screen"] = {
        "grade": "measured (numpy float64)",
        "coverage": {
            "line": "sigma = 7/4 exactly (dyadic, exact in float64)",
            "t_range": [0.0, T_MAX],
            "step": step,
            "step_derivation": "(2 pi / nu_bar) / 8, nu_bar the modulus-"
                               "weighted mean of log p over the head, the "
                               "mean oscillation scale over 8",
            "n_points": screen["n_points"],
            "head_primes_upto": int(primes_head[-1]),
            "n_head_primes": int(primes_head.size),
            "abs_P_vs_abs_F_bound": f"||P| - |F47|| <= T50 = {T50:.6f} pointwise",
            "sigma_sensitivity_note": "a zero at distance d from the line "
                                      "lifts min |P| by roughly 0.3 d "
                                      "(typical |P'|), so the line screen "
                                      "sees only zeros with |Re s - 1.75| "
                                      "of order 0.01 or less",
        },
        "phase_recurrence_max_dev": screen["recurrence_vs_direct_max_dev"],
        "time_s": screen["time_s"],
        "counts_below_thresholds_absF47": screen["counts_below"],
        "coarse_global_min": {"absF47": gmin, "t": gmin_t},
        "coarse_top10_chunk_minima": top10,
        "refinement": {"passA": ref["passA"], "passB": ref["passB"]},
        "global_min_refined": best,
        "candidate_threshold_absP": CANDIDATE_THRESHOLD,
        "candidates_found": int(best["absP_interval"][0] < CANDIDATE_THRESHOLD
                                and best["absP_head_1e6"] < CANDIDATE_THRESHOLD),
    }

    # ---------------- box counter controls (always run) ----------------
    out["box_counter"] = box_counter_controls(screen)

    # ---------------- stage 4 (gated) ----------------
    if best["absP_head_1e6"] < CANDIDATE_THRESHOLD:
        decided_consts = json.load(open(os.path.join(HERE, "decided.json")))["constants"]
        out["candidate_polish"] = polish_and_decide(best["t"], decided_consts)
    else:
        out["candidate_polish"] = {
            "ran": False,
            "reason": f"no refined point reached |P| < {CANDIDATE_THRESHOLD}; "
                      "the gate stays closed",
        }

    witness = bool(out["candidate_polish"].get("witness_decided", False))
    out["verdict"] = {
        "witness_decided_exists": witness,
        "P4_preregistered": "no explicit witness zero below t = 10^8",
        "P4_outcome": "confirmed: the screen found no candidate"
                      if not witness else "REFUTED: a decided witness exists",
        "summary": {
            "eps0_budget_at_sigma1": eps0,
            "min_absP_found": best["absP_head_1e6"],
            "min_absP_location_t": best["t"],
            "expected_t_heuristic_line": t_exp_main,
            "expected_t_heuristic_window": t_exp_win,
        },
    }
    out["total_time_s"] = round(time.perf_counter() - t_start, 1)

    path = os.path.join(HERE, "witness_results.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    print(json.dumps(out["verdict"], indent=2))
    print("wrote", path)


if __name__ == "__main__":
    main()
