import FourPoint.Cover
import FourPoint.Boxes

/-!
# The four-point certificate, and the unconditional bound it discharges

`four_point_cert` proves the hypothesis `hCert` of `Zeta23Ext.Bridge.n_point_bound` at
`n = 4`, `c = 2310/10⁶`, `p = 2500`, so that the `n = 4` instance of that theorem is
**unconditional**.  Generated by `hunts/ainta_seven_point/four_point_gen.py`; see
`hunts/ainta_seven_point/FOUR-POINT.md`.
-/

noncomputable section
-- `HD` lives in `Zeta23.ThmD`, `Ncount` and `N0simple` in `Zeta23.ZeroSide`, and
-- `eventually_atTop` in `Filter`: the same opens `lean/bridge/Zeta23Ext/Bridge/Main.lean`
-- uses.  `autoImplicit` is off in the lakefile, so a missing one is an error rather than
-- a silent auto-bound variable.
open Filter
open Zeta23 Zeta23.ZeroSide Zeta23.ThmD
namespace Zeta23Ext.Bridge.FourPoint

private lemma sum3 (f : Fin (4-1) → ℝ) : ∑ i, f i = f 0 + f 1 + f 2 := by
  show ∑ i : Fin 3, f i = f 0 + f 1 + f 2
  exact Fin.sum_univ_three f

/-- The four-point functional, written out.  The pair coefficient `2/(n − (j−i))` is
`2/3` on the three adjacent pairs, `1` on the two next-nearest pairs and `2` on the
outer pair. -/
lemma F4_eq (p : ℕ) (g : Fin 3 → ℝ) :
    F 4 p g = (1/(p:ℝ)) * (g 0 + g 1 + g 2)
      + 2/3 * wfun (g 0) + 2/3 * wfun (g 1) + 2/3 * wfun (g 2)
      + wfun (g 0 + g 1) + wfun (g 1 + g 2) + 2 * wfun (g 0 + g 1 + g 2) := by
  simp only [F, ptsN, sum3, Fin.sum_univ_four, Fin.isValue]
  norm_num
  -- `norm_num` evaluates the six pair coefficients `2/(4 − (j−i))` and cancels the
  -- telescoping `ptsN` differences; whether it also closes the goal depends on the
  -- association it leaves, so `ring` is optional rather than required.
  try ring

-- The `64`-case analysis, carried by a private lemma so that the advertised
-- `four_point_cert` below is `intro`, `rw` and `exact` at the DEFAULT heartbeat
-- budget.  `set_option maxHeartbeats` is a compile-resource limit and nothing else,
-- it is not an axiom and does not appear in `#print axioms`, but the advertised
-- statements are worth keeping free of it.
set_option maxHeartbeats 20000000 in
private lemma cert_core (x y z : ℝ) (hx0 : 0 ≤ x) (hy0 : 0 ≤ y) (hz0 : 0 ≤ z) :
    (2310/1000000:ℝ) ≤ (1/(2500:ℝ)) * (x + y + z) + 2/3 * wfun x + 2/3 * wfun y + 2/3 * wfun z + wfun (x + y) + wfun (y + z) + 2 * wfun (x + y + z) := by
  have hn0 := wfun_nonneg x
  have hn1 := wfun_nonneg y
  have hn2 := wfun_nonneg z
  have hn3 := wfun_nonneg (x + y)
  have hn4 := wfun_nonneg (y + z)
  have hn5 := wfun_nonneg (x + y + z)
  rcases le_total (231/40:ℝ) (x + y + z) with hS | hS
  · linarith
  have hxS : x ≤ (231/40:ℝ) := by linarith
  have hyS : y ≤ (231/40:ℝ) := by linarith
  have hzS : z ≤ (231/40:ℝ) := by linarith
  rcases cover1 x hx0 hxS with hcx | hbx
  · linarith
  rcases cover1 y hy0 hyS with hcy | hby
  · linarith
  rcases cover1 z hz0 hzS with hcz | hbz
  · linarith
  rcases hbx with hbx0 | hbx1 | hbx2 | hbx3
  all_goals (rcases hby with hby0 | hby1 | hby2 | hby3)
  all_goals (rcases hbz with hbz0 | hbz1 | hbz2 | hbz3)
  · exact box_0_0_0 x y z hbx0.1 hbx0.2 hby0.1 hby0.2 hbz0.1 hbz0.2
  · exact box_0_0_1 x y z hbx0.1 hbx0.2 hby0.1 hby0.2 hbz1.1 hbz1.2
  · exact box_0_0_2 x y z hbx0.1 hbx0.2 hby0.1 hby0.2 hbz2.1 hbz2.2
  · exact box_0_0_3 x y z hbx0.1 hbx0.2 hby0.1 hby0.2 hbz3.1 hbz3.2
  · exact box_0_1_0 x y z hbx0.1 hbx0.2 hby1.1 hby1.2 hbz0.1 hbz0.2
  · exact box_0_1_1 x y z hbx0.1 hbx0.2 hby1.1 hby1.2 hbz1.1 hbz1.2
  · exact box_0_1_2 x y z hbx0.1 hbx0.2 hby1.1 hby1.2 hbz2.1 hbz2.2
  · exfalso; linarith [hbx0.1, hby1.1, hbz3.1]
  · exact box_0_2_0 x y z hbx0.1 hbx0.2 hby2.1 hby2.2 hbz0.1 hbz0.2
  · exact box_0_2_1 x y z hbx0.1 hbx0.2 hby2.1 hby2.2 hbz1.1 hbz1.2
  · exfalso; linarith [hbx0.1, hby2.1, hbz2.1]
  · exfalso; linarith [hbx0.1, hby2.1, hbz3.1]
  · exact box_0_3_0 x y z hbx0.1 hbx0.2 hby3.1 hby3.2 hbz0.1 hbz0.2
  · exfalso; linarith [hbx0.1, hby3.1, hbz1.1]
  · exfalso; linarith [hbx0.1, hby3.1, hbz2.1]
  · exfalso; linarith [hbx0.1, hby3.1, hbz3.1]
  · have h := box_0_0_1 z y x hbz0.1 hbz0.2 hby0.1 hby0.2 hbx1.1 hbx1.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exact box_1_0_1 x y z hbx1.1 hbx1.2 hby0.1 hby0.2 hbz1.1 hbz1.2
  · exact box_1_0_2 x y z hbx1.1 hbx1.2 hby0.1 hby0.2 hbz2.1 hbz2.2
  · exfalso; linarith [hbx1.1, hby0.1, hbz3.1]
  · have h := box_0_1_1 z y x hbz0.1 hbz0.2 hby1.1 hby1.2 hbx1.1 hbx1.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exact box_1_1_1 x y z hbx1.1 hbx1.2 hby1.1 hby1.2 hbz1.1 hbz1.2
  · exfalso; linarith [hbx1.1, hby1.1, hbz2.1]
  · exfalso; linarith [hbx1.1, hby1.1, hbz3.1]
  · have h := box_0_2_1 z y x hbz0.1 hbz0.2 hby2.1 hby2.2 hbx1.1 hbx1.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exfalso; linarith [hbx1.1, hby2.1, hbz1.1]
  · exfalso; linarith [hbx1.1, hby2.1, hbz2.1]
  · exfalso; linarith [hbx1.1, hby2.1, hbz3.1]
  · exfalso; linarith [hbx1.1, hby3.1, hbz0.1]
  · exfalso; linarith [hbx1.1, hby3.1, hbz1.1]
  · exfalso; linarith [hbx1.1, hby3.1, hbz2.1]
  · exfalso; linarith [hbx1.1, hby3.1, hbz3.1]
  · have h := box_0_0_2 z y x hbz0.1 hbz0.2 hby0.1 hby0.2 hbx2.1 hbx2.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · have h := box_1_0_2 z y x hbz1.1 hbz1.2 hby0.1 hby0.2 hbx2.1 hbx2.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exfalso; linarith [hbx2.1, hby0.1, hbz2.1]
  · exfalso; linarith [hbx2.1, hby0.1, hbz3.1]
  · have h := box_0_1_2 z y x hbz0.1 hbz0.2 hby1.1 hby1.2 hbx2.1 hbx2.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exfalso; linarith [hbx2.1, hby1.1, hbz1.1]
  · exfalso; linarith [hbx2.1, hby1.1, hbz2.1]
  · exfalso; linarith [hbx2.1, hby1.1, hbz3.1]
  · exfalso; linarith [hbx2.1, hby2.1, hbz0.1]
  · exfalso; linarith [hbx2.1, hby2.1, hbz1.1]
  · exfalso; linarith [hbx2.1, hby2.1, hbz2.1]
  · exfalso; linarith [hbx2.1, hby2.1, hbz3.1]
  · exfalso; linarith [hbx2.1, hby3.1, hbz0.1]
  · exfalso; linarith [hbx2.1, hby3.1, hbz1.1]
  · exfalso; linarith [hbx2.1, hby3.1, hbz2.1]
  · exfalso; linarith [hbx2.1, hby3.1, hbz3.1]
  · have h := box_0_0_3 z y x hbz0.1 hbz0.2 hby0.1 hby0.2 hbx3.1 hbx3.2
    rw [show z + y + x = x + y + z from by ring,
        show z + y = y + z from by ring,
        show y + x = x + y from by ring] at h
    linarith
  · exfalso; linarith [hbx3.1, hby0.1, hbz1.1]
  · exfalso; linarith [hbx3.1, hby0.1, hbz2.1]
  · exfalso; linarith [hbx3.1, hby0.1, hbz3.1]
  · exfalso; linarith [hbx3.1, hby1.1, hbz0.1]
  · exfalso; linarith [hbx3.1, hby1.1, hbz1.1]
  · exfalso; linarith [hbx3.1, hby1.1, hbz2.1]
  · exfalso; linarith [hbx3.1, hby1.1, hbz3.1]
  · exfalso; linarith [hbx3.1, hby2.1, hbz0.1]
  · exfalso; linarith [hbx3.1, hby2.1, hbz1.1]
  · exfalso; linarith [hbx3.1, hby2.1, hbz2.1]
  · exfalso; linarith [hbx3.1, hby2.1, hbz3.1]
  · exfalso; linarith [hbx3.1, hby3.1, hbz0.1]
  · exfalso; linarith [hbx3.1, hby3.1, hbz1.1]
  · exfalso; linarith [hbx3.1, hby3.1, hbz2.1]
  · exfalso; linarith [hbx3.1, hby3.1, hbz3.1]

/-- **The four-point certificate.**  This is the hypothesis `hCert` of
`Zeta23Ext.Bridge.n_point_bound` at `n = 4`, `c = 2310/10⁶`, `p = 2500`, proved. -/
theorem four_point_cert :
    ∀ g : Fin (4-1) → ℝ, (∀ i, 0 ≤ g i) → (2310/1000000:ℝ) ≤ F 4 2500 g := by
  intro g hg
  rw [F4_eq]
  exact cert_core (g 0) (g 1) (g 2) (hg 0) (hg 1) (hg 2)

/-- `Phi_n 4 c m p` at the certificate's parameters, as an exact rational in `HD 1`. -/
theorem Phi_four : Phi_n 4 (2310/1000000:ℝ) 435 2500 = (906250 * HD 1 - 1085) / 904171 := by
  unfold Phi_n
  push_cast
  -- `1 − c(m−(n−1))/m` and the right denominator are nonzero rationals, so the
  -- identity is a single cross-multiplication with `HD 1` left as an atom.
  rw [div_eq_div_iff (by norm_num) (by norm_num)]
  ring

/-- **The four-point bound, unconditional.**  `Zeta23Ext.Bridge.n_point_bound` at
`n = 4` with its certificate hypothesis discharged by `four_point_cert`: for Mathlib's
`riemannZeta`, for every `ε > 0` and all large `T`, `(Φ₄ − ε) N(T,2T) ≤ N₀ˢ(T,2T)` with
`Φ₄ = (906250 H − 1085)/904171`, `H = HD 1 = 3/2 − (1/√2)cot(1/√2)`. -/
theorem four_point_bound :
    ∀ ε > 0, ∃ T₀ : ℝ, ∀ T ≥ T₀,
      ((906250 * HD 1 - 1085) / 904171 - ε) * (Ncount T (2 * T) : ℝ)
        ≤ N0simple T (2 * T) := by
  rw [← Phi_four]
  exact n_point_bound 4 (2310/1000000:ℝ) 435 2500 (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) four_point_cert (by norm_num)

/-- **The same bound as a proportion.** -/
theorem four_point_bound_ratio :
    ∀ ε > 0, ∃ T₀ : ℝ, ∀ T ≥ T₀,
      (906250 * HD 1 - 1085) / 904171 - ε
        ≤ (N0simple T (2 * T) : ℝ) / (Ncount T (2 * T) : ℝ) := by
  intro ε hε
  obtain ⟨T₁, hT₁⟩ := four_point_bound ε hε
  obtain ⟨T₂, hT₂⟩ := eventually_atTop.mp eventually_Ncount_pos
  refine ⟨max T₁ T₂, fun T hT => ?_⟩
  have h1 := hT₁ T (le_trans (le_max_left _ _) hT)
  have h2 := hT₂ T (le_trans (le_max_right _ _) hT)
  rw [le_div_iff₀ h2]
  exact h1

/-! ### Standing axiom audit (idiom of `Zeta23Ext/Bridge/Defs.lean`) -/

#print axioms F4_eq
#print axioms cover1
#print axioms four_point_cert
#print axioms Phi_four
#print axioms four_point_bound
#print axioms four_point_bound_ratio

end Zeta23Ext.Bridge.FourPoint
