/-
Copyright (c) 2026 Thomas Lince. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Thomas Lince
-/
import Mathlib

/-!
# Finite Abel summation for RAMS2

This module records the exact positive-index Abel identity used by the RAMS2
coefficient-energy layer.  The proof was generated by Harmonic Aristotle in a
minimal Lean 4.28 project and accepted here only after rebuilding it under the
repository's pinned Lean toolchain.
-/

namespace ZetaLean.HigherXi

open Finset

/-- Prefix mass on the positive natural indices through `N`. -/
noncomputable def prefixMass (b : ℕ → ℝ) (N : ℕ) : ℝ :=
  ∑ n ∈ Finset.Icc 1 N, b n

/-- Exact finite Abel summation on the positive natural indices. -/
theorem finite_abel_summation (b w : ℕ → ℝ) (N : ℕ) :
    (∑ n ∈ Finset.Icc 1 N, b n * w n) =
      prefixMass b N * w N +
        ∑ n ∈ Finset.Ico 1 N,
          prefixMass b n * (w n - w (n + 1)) := by
  induction N with
  | zero => simp [prefixMass]
  | succ N ih =>
    have hP : prefixMass b (N + 1) = prefixMass b N + b (N + 1) := by
      simp [prefixMass, Finset.sum_Icc_succ_top (Nat.le_add_left 1 N)]
    rw [Finset.sum_Icc_succ_top (Nat.le_add_left 1 N), ih, hP]
    rcases Nat.eq_zero_or_pos N with hN | hN
    · subst hN
      simp [prefixMass]
      ring
    · rw [Finset.sum_Ico_succ_top hN]
      ring

end ZetaLean.HigherXi
