import Mathlib
import ZetaLean.Rigor
import ZetaLean.DirichletEval

/-!
# Davenport-Heilbronn Oracle Certificate
This file is generated by `oracle_dh.py`.
It provides the certified bounds for the Davenport-Heilbronn function at the off-line zero.
-/

def offline_zero_re : ℚ := 808517 / 1000000
def offline_zero_im : ℚ := 21424837 / 250000


def term_1_bound : BoundedComplex :=
  { re_lb := 1.0,
    re_ub := 1.0,
    im_lb := 0.0,
    im_ub := 0.0,
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }

def term_2_bound : BoundedComplex :=
  { re_lb := -0.54745265636526246778162501277202936010792753207368,
    re_ub := -0.54745265636526127250695607383419425290063943131083,
    im_lb := -0.16217456582807212997590563556943358834925506821038,
    im_ub := -0.16217456582807093470123669663159848114196696744752,
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }

def term_3_bound : BoundedComplex :=
  { re_lb := 0.40942569906019583285992118769231411451917022272227,
    re_ub := 0.40942569906105978980356338871241853808315296200695,
    im_lb := 0.040014057187841846573159399417862737385749899806158,
    im_ub := 0.040014057188705803516801600437967160949732639090836,
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }

def term_4_bound : BoundedComplex :=
  { re_lb := 0.27340382115985730878381295939126373459896690640323,
    re_ub := 0.27340382115985867371212558116455732438006587167768,
    im_lb := 0.17756579371492088741772456658490391533184497062741,
    im_ub := 0.17756579371492225234603718835819750511294393590186,
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }

def term_5_bound : BoundedComplex :=
  { re_lb := 0.25984681080934366384313380358416646857637341136861,
    re_ub := 0.25984681080935436286509790246332581511611548541779,
    im_lb := 0.08103449040666381144125670422192545808521814386322,
    im_ub := 0.081034490406674510463220803101084804624960217912395,
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }

/- 
Note: The Dirichlet series for DH(s) does not converge absolutely at Re(s) ≈ 0.808.
To evaluate DH(s) rigorously, we must use the Hurwitz zeta expansion, 
or approximate the analytic continuation. The above bounds are for $n^{-s}$.
-/
