#!/usr/bin/env python3
"""Emit and time one staged prime exponential tower for rung 3.

This is the cost pilot required before the 215-site run.  It emits the exact
certificate shape planned for a prime: one literal-bounds product for ``-s log m``,
a cached 19-product Taylor power chain, and ten coarsened squarings.  Every
intermediate ball is a literal, so the kernel checks small staged equalities
instead of unfolding one large recursive expression.

Run from the repository root::

    .venv/bin/python scripts/68_rung3_ball_tower_pilot.py --prime 2 --out /tmp/Rung3TowerPilot.lean
    cd lean && /usr/bin/time -p lake env lean /tmp/Rung3TowerPilot.lean
"""
from __future__ import annotations

import argparse
import importlib
import math
import sys
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
ball = importlib.import_module("63_rung3_ball_mirror")

NLOG, NEXP, P, KE = 32, 20, 64, 10
ORACLE = (F(808517, 10**6), F(85699348, 10**6))


def q(x) -> str:
    x = F(x)
    if x.denominator == 1:
        return f"({x.numerator} : ℚ)"
    return f"({x.numerator}/{x.denominator} : ℚ)"


def lit(x) -> str:
    return f"(⟨{q(x.cre)}, {q(x.cim)}, {q(x.rad)}⟩ : ComplexBall)"


def _norm_proof(name: str, value) -> str:
    u = ball._absc_upper(value)
    return (
        f"(ComplexBall.norm_centre_le (x := {name}) (u := {q(u)}) "
        f"(by norm_num) (by norm_num [{name}]))"
    )


def render_prime_tower(prime: int = 2, S=None) -> tuple[str, dict]:
    if prime < 2 or ball._spf(prime) != prime:
        raise ValueError(f"pilot input must be prime, got {prime}")

    if S is None:
        S = ball.C(*ORACLE, 0)
    Sneg = ball.cneg(S)
    log_iv = ball.logQ(NLOG, prime.bit_length(), F(prime))
    L = ball.from_interval(log_iv)
    X = ball.cmul(Sneg, L)
    Y = ball.smulQ(F(1, 2**KE), X)

    powers = [ball.cexact(1, 0)]
    for _ in range(1, NEXP):
        powers.append(ball.cmul(powers[-1], Y))
    terms = [ball.smulQ(F(1, math.factorial(i)), powers[i]) for i in range(NEXP)]
    sums = [ball.cexact(0, 0)]
    for term in terms:
        sums.append(ball.cadd(sums[-1], term))

    y_bound = ball.normBound(Y)
    remainder = y_bound**NEXP * F(NEXP + 1, math.factorial(NEXP) * NEXP)
    small = ball.cinflate(sums[-1], remainder)
    square_values = [ball.ccoarsen(P, small)]
    for _ in range(KE):
        square_values.append(ball.ccoarsen(P, ball.cmul(square_values[-1], square_values[-1])))
    final = square_values[-1]

    lines: list[str] = []
    a = lines.append
    a("/- Generated by scripts/68_rung3_ball_tower_pilot.py. -/")
    a("import ZetaLean.BallTerm")
    a("")
    a("open Complex Finset ZetaLean ZetaLean.ComplexBall")
    a("")
    a("set_option maxRecDepth 8000000")
    a("set_option maxHeartbeats 40000000")
    a("")
    a("namespace ZetaLean.Rung3TowerPilot")
    a("")
    a(f"def S : ComplexBall := {lit(S)}")
    a(f"def Sneg : ComplexBall := {lit(Sneg)}")
    a(f"def L : ComplexBall := {lit(L)}")
    a(f"def X : ComplexBall := {lit(X)}")
    a(f"def Y : ComplexBall := {lit(Y)}")
    a("")
    a("private lemma ev_neg : S.neg = Sneg := by")
    a("  norm_num [S, Sneg, ComplexBall.neg]")
    a("")
    a(f"private lemma ev_log : ofRealInterval (Interval.logQ {NLOG} {prime.bit_length()} ({prime} : ℚ)) = L := by")
    a("  norm_num [L, ofRealInterval, Interval.logQ, Interval.log2I, Interval.log1,")
    a("    Interval.logSum, Interval.logRem, Interval.exact, Interval.mul, Interval.add,")
    a("    Interval.neg, Interval.sub, Nat.factorial, Finset.sum_range_succ,")
    a("    Finset.sum_range_zero]")
    a("")

    atom = 0
    ux, uL = ball._absc_upper(Sneg), ball._absc_upper(L)
    a(f"private lemma ev_mul_{atom:02d} : ComplexBall.mul Sneg L {q(ux)} {q(uL)} = X := by")
    a("  norm_num [Sneg, L, X, ComplexBall.mul]")
    a("")
    atom += 1

    a(f"private lemma ev_scale : smulQ {q(F(1, 2**KE))} X = Y := by")
    a("  norm_num [X, Y, smulQ]")
    a("")

    a(f"def Pow_0 : ComplexBall := {lit(powers[0])}")
    for i in range(1, NEXP):
        a(f"def Pow_{i} : ComplexBall := {lit(powers[i])}")
        up, uy = ball._absc_upper(powers[i - 1]), ball._absc_upper(Y)
        a(f"private lemma ev_mul_{atom:02d} : ComplexBall.mul Pow_{i - 1} Y {q(up)} {q(uy)} = Pow_{i} := by")
        a(f"  norm_num [Pow_{i - 1}, Y, Pow_{i}, ComplexBall.mul]")
        a("")
        atom += 1

    for i, term in enumerate(terms):
        a(f"def Term_{i} : ComplexBall := {lit(term)}")
        a(f"private lemma ev_term_{i} : smulQ {q(F(1, math.factorial(i)))} Pow_{i} = Term_{i} := by")
        a(f"  norm_num [Pow_{i}, Term_{i}, smulQ]")
        a("")

    a(f"def Sum_0 : ComplexBall := {lit(sums[0])}")
    for i in range(NEXP):
        a(f"def Sum_{i + 1} : ComplexBall := {lit(sums[i + 1])}")
        a(f"private lemma ev_sum_{i} : Sum_{i}.add Term_{i} = Sum_{i + 1} := by")
        a(f"  norm_num [Sum_{i}, Term_{i}, Sum_{i + 1}, ComplexBall.add]")
        a("")

    a(f"def Small : ComplexBall := {lit(small)}")
    a(f"private lemma ev_small : Sum_{NEXP}.inflate {q(remainder)} = Small := by")
    a(f"  norm_num [Sum_{NEXP}, Small, inflate]")
    a("")
    a(f"def Sq_0 : ComplexBall := {lit(square_values[0])}")
    a(f"private lemma ev_base : coarsenB {P} Small = Sq_0 := by")
    a("  norm_num [Small, Sq_0, coarsenB, recentre, widenRad, ceilP]")
    a("")

    for i in range(KE):
        prev, nxt = square_values[i], square_values[i + 1]
        u = ball._absc_upper(prev)
        a(f"def Sq_{i + 1} : ComplexBall := {lit(nxt)}")
        a(f"private lemma ev_mul_{atom:02d} : coarsenB {P} (ComplexBall.mul Sq_{i} Sq_{i} {q(u)} {q(u)}) = Sq_{i + 1} := by")
        a(f"  norm_num [Sq_{i}, Sq_{i + 1}, coarsenB, recentre, widenRad, ceilP,")
        a("    ComplexBall.mul]")
        a("")
        atom += 1

    assert atom == 30, atom

    log_real = f"((Real.log {prime} : ℝ) : ℂ)"
    xval = f"(-s) * {log_real}"
    yval = f"(({q(F(1, 2**KE))} : ℂ) * ({xval}))"
    a(f"theorem pilot_contains_cpow {{s : ℂ}} (hS : S.contains s) :")
    a(f"    Sq_{KE}.contains ((({prime} : ℕ) : ℂ) ^ (-s)) := by")
    a("  have hSneg0 := ComplexBall.contains_neg hS")
    a("  rw [ev_neg] at hSneg0")
    a("  have hlog0 := Interval.contains_logQ")
    a(f"    (n := {NLOG}) (k := {prime.bit_length()}) (q := ({prime} : ℚ)) (by norm_num) (by norm_num)")
    a(f"  rw [show ((({prime} : ℚ) : ℝ)) = (({prime} : ℕ) : ℝ) by push_cast; rfl] at hlog0")
    a("  have hL0 := ComplexBall.contains_ofRealInterval hlog0")
    a("  rw [ev_log] at hL0")
    a(f"  have hX0 : (ComplexBall.mul Sneg L {q(ux)} {q(uL)}).contains ({xval}) :=")
    a(f"    ComplexBall.contains_mul {_norm_proof('Sneg', Sneg)} {_norm_proof('L', L)} hSneg0 hL0")
    a("  rw [ev_mul_00] at hX0")
    a(f"  have hY0 := ComplexBall.contains_smulQ (q := {q(F(1, 2**KE))}) hX0")
    a("  rw [ev_scale] at hY0")
    a(f"  have hY : Y.contains ({yval}) := hY0")
    a("  have hPow_0 : Pow_0.contains ((" + yval + ") ^ 0) := by")
    a("    have h := ComplexBall.contains_exact (1 : ℚ) (0 : ℚ)")
    a("    rw [show (⟨((1 : ℚ) : ℝ), ((0 : ℚ) : ℝ)⟩ : ℂ) = (1 : ℂ) by")
    a("      apply Complex.ext <;> norm_num] at h")
    a("    simpa [Pow_0, ComplexBall.exact] using h")

    power_atom = 1
    for i in range(1, NEXP):
        prev = powers[i - 1]
        a(f"  have hp_{i} := ComplexBall.contains_mul {_norm_proof(f'Pow_{i - 1}', prev)} {_norm_proof('Y', Y)} hPow_{i - 1} hY")
        a(f"  rw [ev_mul_{power_atom:02d}] at hp_{i}")
        a(f"  have hPow_{i} : Pow_{i}.contains (({yval}) ^ {i}) := by")
        a(f"    simpa [pow_succ] using hp_{i}")
        power_atom += 1

    for i in range(NEXP):
        a(f"  have ht_{i} := ComplexBall.contains_smulQ (q := {q(F(1, math.factorial(i)))}) hPow_{i}")
        a(f"  rw [ev_term_{i}] at ht_{i}")
        a(f"  have hTerm_{i} : Term_{i}.contains (({yval}) ^ {i} / ({i} : ℕ).factorial) := by")
        a(f"    convert ht_{i} using 1 <;> push_cast <;> ring")

    a("  have hSum_0 : Sum_0.contains (∑ i ∈ range 0, (" + yval + ") ^ i / i.factorial) := by")
    a("    have h := ComplexBall.contains_exact (0 : ℚ) (0 : ℚ)")
    a("    rw [show (⟨((0 : ℚ) : ℝ), ((0 : ℚ) : ℝ)⟩ : ℂ) = (0 : ℂ) by")
    a("      apply Complex.ext <;> norm_num] at h")
    a("    simpa [Sum_0, ComplexBall.exact] using h")
    for i in range(NEXP):
        a(f"  have hs_{i} := ComplexBall.contains_add hSum_{i} hTerm_{i}")
        a(f"  rw [ev_sum_{i}] at hs_{i}")
        a(f"  have hSum_{i + 1} : Sum_{i + 1}.contains")
        a(f"      (∑ j ∈ range {i + 1}, ({yval}) ^ j / j.factorial) := by")
        a("    rw [Finset.sum_range_succ]")
        a(f"    exact hs_{i}")

    uy = ball._absc_upper(Y)
    fac_expr = (f"(((Nat.succ {NEXP} : ℕ) : ℝ) * "
                f"(((({NEXP} : ℕ).factorial : ℝ) * ({NEXP} : ℝ))⁻¹))")
    a(f"  have hYbound : ‖({yval})‖ ≤ (({q(y_bound)}) : ℝ) := by")
    a(f"    have h := ComplexBall.norm_le_normBound {_norm_proof('Y', Y)} hY")
    a(f"    convert h using 1 <;> norm_num [Y]")
    a(f"  have hYone : ‖({yval})‖ ≤ 1 := hYbound.trans (by norm_num)")
    a(f"  have hexp := Complex.exp_bound hYone (by norm_num : 0 < {NEXP})")
    a(f"  have hpow : ‖({yval})‖ ^ {NEXP} ≤ (({q(y_bound)}) : ℝ) ^ {NEXP} :=")
    a(f"    pow_le_pow_left₀ (norm_nonneg _) hYbound {NEXP}")
    a(f"  have hfac : (0 : ℝ) ≤ {fac_expr} := by positivity")
    a(f"  have hrem : ‖Complex.exp ({yval})")
    a(f"        - ∑ i ∈ range {NEXP}, ({yval}) ^ i / i.factorial‖ ≤ (({q(remainder)}) : ℝ) := by")
    a("    refine hexp.trans ?_")
    a("    calc")
    a(f"      ‖({yval})‖ ^ {NEXP} * {fac_expr}")
    a(f"          ≤ (({q(y_bound)}) : ℝ) ^ {NEXP} * {fac_expr} :=")
    a("            mul_le_mul_of_nonneg_right hpow hfac")
    a(f"      _ = (({q(remainder)}) : ℝ) := by norm_num")
    a(f"  have hSmall0 := ComplexBall.contains_inflate_of_dist {q(remainder)} hSum_{NEXP} hrem")
    a("  rw [ev_small] at hSmall0")
    a(f"  have hSq_0 : Sq_0.contains (Complex.exp ({yval})) := by")
    a("    rw [← ev_base]")
    a("    exact ComplexBall.contains_coarsenB _ hSmall0")

    square_atom_start = 20
    for i in range(KE):
        prev = square_values[i]
        exponent = 2 ** (i + 1)
        a(f"  have hsquare_{i} := ComplexBall.contains_coarsenB {P}")
        a(f"    (ComplexBall.contains_mul {_norm_proof(f'Sq_{i}', prev)} {_norm_proof(f'Sq_{i}', prev)} hSq_{i} hSq_{i})")
        a(f"  rw [ev_mul_{square_atom_start + i:02d}] at hsquare_{i}")
        a(f"  have hSq_{i + 1} : Sq_{i + 1}.contains ((Complex.exp ({yval})) ^ {exponent}) := by")
        if i == 0:
            a(f"    simpa [pow_two] using hsquare_{i}")
        else:
            prev_exp = 2 ** i
            a(f"    rw [show (Complex.exp ({yval})) ^ {exponent}")
            a(f"        = (Complex.exp ({yval}) ^ {prev_exp}) * (Complex.exp ({yval}) ^ {prev_exp}) by")
            a("          rw [← pow_add]]")
            a(f"    exact hsquare_{i}")

    a(f"  have hfinal : Sq_{KE}.contains (Complex.exp ({xval})) := by")
    a(f"    rw [← show (Complex.exp ({yval})) ^ (2 ^ {KE}) = Complex.exp ({xval}) by")
    a("      rw [← Complex.exp_nat_mul]")
    a("      congr 1")
    a("      push_cast")
    a("      field_simp]")
    a(f"    simpa using hSq_{KE}")
    a(f"  have hm0 : (({prime} : ℕ) : ℂ) ≠ 0 := by norm_num")
    a(f"  rw [show ((({prime} : ℕ) : ℂ) ^ (-s)) = Complex.exp ({xval}) by")
    a(f"    have hlog : Complex.log (({prime} : ℕ) : ℂ) = {log_real} := by")
    a(f"      simpa using (Complex.ofReal_log (by positivity : (0 : ℝ) ≤ (({prime} : ℕ) : ℝ)))")
    a("    rw [Complex.cpow_def_of_ne_zero hm0, hlog, mul_comm]]")
    a("  exact hfinal")
    a("")
    a("end ZetaLean.Rung3TowerPilot")
    a("")

    stats = {
        "prime": prime,
        "product_atoms": atom,
        "final": final,
        "max_power_den_bits": max(
            max(x.cre.denominator.bit_length(), x.cim.denominator.bit_length(),
                x.rad.denominator.bit_length()) for x in powers
        ),
    }
    return "\n".join(lines), stats


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prime", type=int, default=2)
    ap.add_argument("--site", help="use this big-box site instead of the oracle point")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    S = None
    if args.site:
        import json
        plan = json.loads((ROOT / "lean" / "cert" / "rung3_plan2.json").read_text())
        try:
            site = next(x for x in plan["big"]["boxes"] if x["id"] == args.site)
        except StopIteration as exc:
            raise SystemExit(f"unknown big-box site: {args.site}") from exc
        S = ball.from_box(site["re_lo"], site["re_hi"], site["im_lo"], site["im_hi"])
    text, stats = render_prime_tower(args.prime, S=S)
    Path(args.out).write_text(text)
    print(f"wrote {args.out}")
    print(f"prime={stats['prime']} product_atoms={stats['product_atoms']} "
          f"max_power_den_bits={stats['max_power_den_bits']}")


if __name__ == "__main__":
    main()
