#!/usr/bin/env python3
"""Ball-certificate backend for ``60_rung3_generate.py``.

Prime powers use the staged tower proven by script 68.  Composite bases reuse
cached factors and emit one coarsened ``ComplexBall.mul`` with both modulus
bounds as rational literals.  The final order-2 assembly stays in balls until
the analytic tail theorem consumes it.

One-file emission is the default.  ``emit_site_ball_modules`` splits a large
site into importable Lean modules whose files stay under ``MAX_SHARD_BYTES``.
Sharded emission also writes a compact per-site JSON manifest naming the
exact relative module order and same-site import dependencies a compile
driver must use.
"""
from __future__ import annotations

import importlib.util
import json
import math
from fractions import Fraction as F
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parent.parent


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / filename)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ball = _load("rung3_ball_mirror_for_generator", "63_rung3_ball_mirror.py")
tower = _load("rung3_ball_tower_for_generator", "68_rung3_ball_tower_pilot.py")

NLOG, NEXP, P, KE = 32, 20, 64, 10
CHUNK = 25
BETA_BITS = 40
MAX_SHARD_BYTES = 2_000_000
MANIFEST_FORMAT_VERSION = 2
GENERATED_BANNER = "/- Generated by scripts/60_rung3_generate.py --arith ball. -/"


def q(x) -> str:
    x = F(x)
    if x.denominator == 1:
        return f"({x.numerator} : ℚ)"
    return f"({x.numerator}/{x.denominator} : ℚ)"


def lit(x) -> str:
    return f"(⟨{q(x.cre)}, {q(x.cim)}, {q(x.rad)}⟩ : ComplexBall)"


def beta_literal(nl: F) -> F:
    scale = 1 << BETA_BITS
    return F(int(nl * scale), scale)


def _norm_proof(expr: str, value, simp: str = "") -> str:
    u = ball._absc_upper(value)
    close = f"(by norm_num [{simp}])" if simp else "(by norm_num)"
    return (
        f"(ComplexBall.norm_centre_le (x := {expr}) (u := {q(u)}) "
        f"(by norm_num) {close})"
    )


def _lower_norm_proof(expr: str, value, simp: str = "") -> tuple[F, str]:
    lo = ball._absc_lower(value)
    close = f"(by norm_num [{simp}])" if simp else "(by norm_num)"
    proof = (
        f"(ComplexBall.le_norm_centre (x := {expr}) (l := {q(lo)}) "
        f"(by norm_num) {close})"
    )
    return lo, proof


def _tower_fragment(prime: int, S, namespace: str) -> tuple[str, object]:
    text, stats = tower.render_prime_tower(prime, S=S)
    marker = "namespace ZetaLean.Rung3TowerPilot\n\n"
    body = text.split(marker, 1)[1].rsplit("\nend ZetaLean.Rung3TowerPilot", 1)[0]
    return f"namespace {namespace}\n\n{body}\n\nend {namespace}\n", stats["final"]


def _needed_powers(N: int) -> list[int]:
    values = [m for m in range(1, N) if m % 5]
    values.extend(range(N + 1, N + 5))
    return values


def _lemma_kw(exported: bool) -> str:
    return "lemma" if exported else "private lemma"


def module_root(sid: str) -> str:
    return f"C{sid}"


def _prepare_site(site: dict, kind: str) -> SimpleNamespace:
    sid = site["id"]
    K, N = int(site["K"]), 5 * int(site["K"])
    relo, rehi = F(site["re_lo"]), F(site["re_hi"])
    imlo, imhi = F(site["im_lo"]), F(site["im_hi"])
    tail_r = F(site["r"])
    SI, SB = f"SI_{sid}", f"S_{sid}"

    Sval = ball.from_box(relo, rehi, imlo, imhi)
    half_width = Sval.rad

    pow_values: dict[int, object] = {}
    pow_kind: dict[int, tuple] = {}
    pow_order: list[int] = []
    prime_fragments: dict[int, str] = {}

    def ensure_power(m: int) -> None:
        if m in pow_values:
            return
        if m == 1:
            value = ball.cexact(1, 0)
            pow_kind[m] = ("one",)
        else:
            f = ball._spf(m)
            if f == m:
                fragment, value = _tower_fragment(m, Sval, f"Prime_{m}")
                prime_fragments[m] = fragment
                pow_kind[m] = ("prime",)
            else:
                b = m // f
                ensure_power(f)
                ensure_power(b)
                raw = ball.cmul(pow_values[f], pow_values[b])
                value = ball.ccoarsen(P, raw)
                pow_kind[m] = ("composite", f, b)
        pow_values[m] = value
        pow_order.append(m)

    needed = _needed_powers(N)
    for m in needed:
        ensure_power(m)

    term_values = {0: ball.cexact(0, 0)}
    for m in range(1, N):
        if m % 5 == 0:
            term_values[m] = ball.cexact(0, 0)
        else:
            term_values[m] = ball.cmul(ball.coeffBox(m), pow_values[m])

    partial = {0: ball.cexact(0, 0)}
    for m in range(N):
        partial[m + 1] = ball.cadd(partial[m], term_values[m])

    m1, m2, m3, m4 = N + 1, N + 2, N + 3, N + 4
    t1, t2, t3, t4 = (pow_values[m] for m in (m1, m2, m3, m4))
    pair = ball.cadd(t2, ball.cneg(t3))
    block_prod = ball.cmul(ball.KAPPA_C, pair)
    block = ball.cadd(ball.cadd(t1, ball.cneg(t4)), block_prod)

    five_one_sub = ball.inv5sBox(Sval)
    anti_v = ball.invC(five_one_sub)
    e1, e2 = ball.smulQ(m1, t1), ball.smulQ(m2, t2)
    e3, e4 = ball.smulQ(m3, t3), ball.smulQ(m4, t4)
    anti_pair = ball.cadd(e2, ball.cneg(e3))
    anti_kprod = ball.cmul(ball.KAPPA_C, anti_pair)
    anti_sum = ball.cadd(ball.cadd(e1, ball.cneg(e4)), anti_kprod)
    anti = ball.cmul(anti_sum, anti_v)
    corrected = ball.cadd(
        ball.cadd(partial[N], ball.smulQ(F(1, 2), block)), ball.cneg(anti))
    inflated = ball.cinflate(corrected, tail_r)
    stats = {
        "id": sid,
        "kind": kind,
        "K": K,
        "normLower": ball.normLower(inflated),
        "normBound": ball.normBound(inflated),
        "prime_towers": len(prime_fragments),
    }
    return SimpleNamespace(
        site=site, kind=kind, sid=sid, K=K, N=N,
        relo=relo, rehi=rehi, imlo=imlo, imhi=imhi, tail_r=tail_r,
        SI=SI, SB=SB, Sval=Sval, half_width=half_width,
        pow_values=pow_values, pow_kind=pow_kind, pow_order=pow_order,
        prime_fragments=prime_fragments, term_values=term_values,
        partial=partial, m1=m1, m2=m2, m3=m3, m4=m4,
        pair=pair, block=block, five_one_sub=five_one_sub, anti_v=anti_v,
        anti_pair=anti_pair, anti_sum=anti_sum, anti=anti,
        corrected=corrected, inflated=inflated, stats=stats,
    )


def emit_site_ball(site: dict, kind: str) -> tuple[str, dict]:
    b = _prepare_site(site, kind)
    sid, K, N = b.sid, b.K, b.N
    relo, rehi, imlo, imhi = b.relo, b.rehi, b.imlo, b.imhi
    tail_r, SI, SB = b.tail_r, b.SI, b.SB
    Sval, half_width = b.Sval, b.half_width
    pow_values, pow_kind, pow_order = b.pow_values, b.pow_kind, b.pow_order
    prime_fragments = b.prime_fragments
    term_values, partial = b.term_values, b.partial
    m1, m2, m3, m4 = b.m1, b.m2, b.m3, b.m4
    pair, block = b.pair, b.block
    five_one_sub, anti_v = b.five_one_sub, b.anti_v
    anti_pair, anti_sum, anti = b.anti_pair, b.anti_sum, b.anti
    corrected, inflated, stats = b.corrected, b.inflated, b.stats

    lines: list[str] = []
    a = lines.append
    a("/- Generated by scripts/60_rung3_generate.py --arith ball. -/")
    a("import ZetaLean.BallCertSupport")
    a("")
    a("open Complex Finset ZetaLean ZetaLean.ComplexBall ZetaLean.DH")
    a("")
    a("set_option maxRecDepth 8000000")
    a("set_option maxHeartbeats 40000000")
    a("")
    a("namespace ZetaLean.DH.Cert")
    a("")
    a(f"def {SI} : ComplexInterval :=")
    a(f"  ⟨⟨{q(relo)}, {q(rehi)}, by norm_num⟩, ⟨{q(imlo)}, {q(imhi)}, by norm_num⟩⟩")
    a("")
    a(f"def {SB} : ComplexBall := {lit(Sval)}")
    a("")
    a(f"private lemma contains_{SB} {{s : ℂ}} (hS : {SI}.contains s) : {SB}.contains s := by")
    a(f"  have h := ComplexBall.contains_ofInterval (B := {SI}) (hw := {q(half_width)}) hS")
    a(f"    (by norm_num [{SI}]) (by norm_num)")
    a(f"  convert h using 1 <;> norm_num [{SB}, {SI}, ComplexBall.ofInterval]")
    a("")

    for p in sorted(prime_fragments):
        a(prime_fragments[p])

    for m in pow_order:
        name = f"Pow_{sid}_{m}"
        value = pow_values[m]
        a(f"def {name} : ComplexBall := {lit(value)}")
        mode = pow_kind[m]
        if mode[0] == "one":
            a(f"private lemma hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
            a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
            a("  have h := ComplexBall.contains_exact (1 : ℚ) (0 : ℚ)")
            a("  rw [show (⟨((1 : ℚ) : ℝ), ((0 : ℚ) : ℝ)⟩ : ℂ) = (1 : ℂ) by")
            a("    apply Complex.ext <;> norm_num] at h")
            a(f"  simpa [{name}, ComplexBall.exact] using h")
        elif mode[0] == "prime":
            a(f"private lemma hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
            a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
            a(f"  have hSp : Prime_{m}.S.contains s := by")
            a(f"    simpa [Prime_{m}.S, {SB}] using hS")
            a(f"  have h := Prime_{m}.pilot_contains_cpow hSp")
            a(f"  simpa [{name}, Prime_{m}.Sq_{KE}] using h")
        else:
            _, left, right = mode
            left_name, right_name = f"Pow_{sid}_{left}", f"Pow_{sid}_{right}"
            ul, ur = ball._absc_upper(pow_values[left]), ball._absc_upper(pow_values[right])
            a(f"private lemma evpow_{sid}_{m} :")
            a(f"    coarsenB {P} (ComplexBall.mul {left_name} {right_name} {q(ul)} {q(ur)}) =")
            a(f"      {name} := by")
            a(f"  norm_num [{left_name}, {right_name}, {name}, coarsenB, recentre, widenRad,")
            a("    ceilP, ComplexBall.mul]")
            a(f"private lemma hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
            a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
            a(f"  have h := contains_cpow_mulB_coarsen_lit {P}")
            a(f"    {_norm_proof(left_name, pow_values[left], left_name)}")
            a(f"    {_norm_proof(right_name, pow_values[right], right_name)}")
            a(f"    (hp_{sid}_{left} hS) (hp_{sid}_{right} hS)")
            a(f"  rw [evpow_{sid}_{m}] at h")
            a(f"  simpa using h")
        a("")

    kappa_simp = (
        "coeffBall, kappaBall, ofRealInterval, DH.kappaI, ComplexBall.exact, "
        "ComplexBall.neg")
    for m in range(N):
        tname = f"Term_{sid}_{m}"
        a(f"def {tname} : ComplexBall := {lit(term_values[m])}")
        if m % 5 == 0:
            a(f"private lemma hterm_{sid}_{m} {{s : ℂ}} :")
            a(f"    {tname}.contains ((dh_coeff {m} : ℂ) * (({m} : ℕ) : ℂ) ^ (-s)) := by")
            a(f"  simpa [{tname}, ComplexBall.exact] using "
              f"(ComplexBall.contains_coeff_term_zero (s := s) {m} (by norm_num [dh_coeff]))")
        else:
            pname = f"Pow_{sid}_{m}"
            uc = ball._absc_upper(ball.coeffBox(m))
            up = ball._absc_upper(pow_values[m])
            a(f"private lemma evterm_{sid}_{m} :")
            a(f"    ComplexBall.mul (coeffBall {m}) {pname} {q(uc)} {q(up)} = {tname} := by")
            a(f"  norm_num [{pname}, {tname}, {kappa_simp}, ComplexBall.mul]")
            a(f"private lemma hterm_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
            a(f"    {tname}.contains ((dh_coeff {m} : ℂ) * (({m} : ℕ) : ℂ) ^ (-s)) := by")
            a(f"  have h := ComplexBall.contains_coeff_term_ne {m} (by norm_num)")
            a(f"    {_norm_proof(f'(coeffBall {m})', ball.coeffBox(m), kappa_simp)}")
            a(f"    {_norm_proof(pname, pow_values[m], pname)} (hp_{sid}_{m} hS)")
            a(f"  rw [evterm_{sid}_{m}] at h")
            a("  exact h")
        a("")

    a(f"def term_{sid} : ℕ → ComplexBall")
    for m in range(N):
        a(f"  | {m} => Term_{sid}_{m}")
    a("  | _ => ComplexBall.exact 0 0")
    a("")
    for m in range(N):
        a(f"private lemma evfun_{sid}_{m} : term_{sid} {m} = Term_{sid}_{m} := rfl")
    a("")
    a(f"private lemma ht_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    ∀ m, m < {N} → (term_{sid} m).contains")
    a("      ((dh_coeff m : ℂ) * (m : ℂ) ^ (-s)) :=")
    a("  fun m hm =>")
    a("    match m, hm with")
    for m in range(N):
        suffix = "" if m % 5 == 0 else " hS"
        a(f"    | {m}, _ => by simpa [evfun_{sid}_{m}] using hterm_{sid}_{m}{suffix}")
    a(f"    | (n + {N}), hm => absurd hm (by omega)")
    a("")

    bounds = sorted(set(list(range(0, N, CHUNK)) + [N]))
    a(f"private lemma ps_{sid}_0 : dhSumBalls (term_{sid}) 0 = {lit(partial[0])} := rfl")
    a("")
    for lo, hi in zip(bounds, bounds[1:]):
        rws: list[str] = []
        for n in range(hi, lo, -1):
            rws.extend((f"show ({n} : ℕ) = {n - 1} + 1 from rfl", "dhSumBalls_succ"))
        rws.append(f"ps_{sid}_{lo}")
        rws.extend(f"evfun_{sid}_{n}" for n in range(lo, hi))
        a(f"private lemma ps_{sid}_{hi} : dhSumBalls (term_{sid}) {hi} =")
        a(f"    {lit(partial[hi])} := by")
        a("  rw [" + ",\n    ".join(rws) + "]")
        term_defs = ", ".join(f"Term_{sid}_{n}" for n in range(lo, hi))
        a(f"  norm_num [{term_defs}, ComplexBall.add]")
        a("")

    pnames = {m: f"Pow_{sid}_{m}" for m in (m1, m2, m3, m4)}
    pair_expr = f"({pnames[m2]}.add {pnames[m3]}.neg)"
    uk, upair = ball._absc_upper(ball.KAPPA_C), ball._absc_upper(pair)
    block_expr = (
        f"(({pnames[m1]}.add {pnames[m4]}.neg).add "
        f"(ComplexBall.mul kappaBall {pair_expr} {q(uk)} {q(upair)}))")
    a(f"def Block_{sid} : ComplexBall := {lit(block)}")
    a(f"private lemma evblock_{sid} : {block_expr} = Block_{sid} := by")
    a(f"  norm_num [{', '.join(pnames.values())}, Block_{sid}, kappaBall, ofRealInterval,")
    a("    DH.kappaI, ComplexBall.add, ComplexBall.neg, ComplexBall.mul]")
    a("")

    one_minus = ball.cadd(ball.cexact(1, 0), ball.cneg(Sval))
    u_one_minus = ball._absc_upper(one_minus)
    lower5, lower5proof = _lower_norm_proof(
        f"(fiveOneSubBall {SB} {q(u_one_minus)})", five_one_sub,
        f"{SB}, fiveOneSubBall, ComplexBall.exact, ComplexBall.add, ComplexBall.neg, ComplexBall.mul")
    a(f"def AntiV_{sid} : ComplexBall := {lit(anti_v)}")
    a(f"private lemma evV_{sid} :")
    a(f"    (fiveOneSubBall {SB} {q(u_one_minus)}).inv {q(anti_v.rad)} = AntiV_{sid} := by")
    a(f"  norm_num [{SB}, AntiV_{sid}, fiveOneSubBall, ComplexBall.exact, ComplexBall.add,")
    a("    ComplexBall.neg, ComplexBall.mul, ComplexBall.inv]")
    a("")
    a(f"private lemma hV_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    AntiV_{sid}.contains ((5 * (1 - s))⁻¹) := by")
    a(f"  have h := contains_inv5sBall (u := {q(u_one_minus)}) (l := {q(lower5)})")
    a(f"    (R := {q(anti_v.rad)}) hS")
    a(f"    {_norm_proof(f'((ComplexBall.exact 1 0).add {SB}.neg)', one_minus, f'{SB}, ComplexBall.exact, ComplexBall.add, ComplexBall.neg')}")
    a("    (by norm_num)")
    a(f"    {lower5proof} (by norm_num [fiveOneSubBall, {SB}, ComplexBall.exact,")
    a("      ComplexBall.add, ComplexBall.neg, ComplexBall.mul])")
    a(f"    (by norm_num [fiveOneSubBall, {SB}, ComplexBall.exact, ComplexBall.add,")
    a("      ComplexBall.neg, ComplexBall.mul])")
    a(f"  rw [evV_{sid}] at h")
    a("  exact h")
    a("")

    qm1 = f"({K} * 5 + 1 : ℚ)"
    qm2 = f"({K} * 5 + 2 : ℚ)"
    qm3 = f"({K} * 5 + 3 : ℚ)"
    qm4 = f"({K} * 5 + 4 : ℚ)"
    anti_pair_expr = (
        f"((smulQ {qm2} {pnames[m2]}).add "
        f"(smulQ {qm3} {pnames[m3]}).neg)")
    uapair = ball._absc_upper(anti_pair)
    anti_sum_expr = (
        f"(((smulQ {qm1} {pnames[m1]}).add "
        f"(smulQ {qm4} {pnames[m4]}).neg).add "
        f"(ComplexBall.mul kappaBall {anti_pair_expr} {q(uk)} {q(uapair)}))")
    usum, uv = ball._absc_upper(anti_sum), ball._absc_upper(anti_v)
    anti_expr = f"(ComplexBall.mul {anti_sum_expr} AntiV_{sid} {q(usum)} {q(uv)})"
    a(f"def Anti_{sid} : ComplexBall := {lit(anti)}")
    a(f"private lemma evanti_{sid} : {anti_expr} = Anti_{sid} := by")
    a(f"  norm_num [{', '.join(pnames.values())}, AntiV_{sid}, Anti_{sid}, kappaBall,")
    a("    ofRealInterval, DH.kappaI, smulQ, ComplexBall.add, ComplexBall.neg, ComplexBall.mul]")
    a("")

    correction_simp = (
        f"{', '.join(pnames.values())}, kappaBall, ofRealInterval, DH.kappaI, "
        "smulQ, ComplexBall.add, ComplexBall.neg, ComplexBall.mul")
    a(f"private lemma hBlock_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    Block_{sid}.contains (dhBlock s {K}) := by")
    a(f"  have h := contains_dhBlock_of_terms_ball (s := s) {K}")
    for m in (m1, m2, m3, m4):
        a(f"    (hp_{sid}_{m} hS)")
    a(f"    {_norm_proof('kappaBall', ball.KAPPA_C, 'kappaBall, ofRealInterval, DH.kappaI')}")
    a(f"    {_norm_proof(pair_expr, pair, correction_simp)}")
    a(f"  rw [evblock_{sid}] at h")
    a("  exact h")
    a("")
    a(f"private lemma hAnti_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    Anti_{sid}.contains (dhAnti s ({K} : ℝ)) := by")
    a(f"  have h := contains_dhAnti_of_terms_ball (s := s) {K}")
    for m in (m1, m2, m3, m4):
        a(f"    (hp_{sid}_{m} hS)")
    a(f"    (hV_{sid} hS)")
    a(f"    {_norm_proof('kappaBall', ball.KAPPA_C, 'kappaBall, ofRealInterval, DH.kappaI')}")
    a(f"    {_norm_proof(anti_pair_expr, anti_pair, correction_simp)}")
    a(f"    {_norm_proof(anti_sum_expr, anti_sum, correction_simp)}")
    a(f"    {_norm_proof(f'AntiV_{sid}', anti_v, f'AntiV_{sid}')}")
    a("  norm_num at h")
    a(f"  have hev := evanti_{sid}")
    a("  norm_num at hev")
    a("  rw [hev] at h")
    a("  exact h")
    a("")

    a(f"def B_{sid} : ComplexBall := {lit(corrected)}")
    corrected_expr = (
        f"((dhSumBalls (term_{sid}) {N}).add (smulQ (1/2 : ℚ) Block_{sid})).add "
        f"Anti_{sid}.neg"
    )
    a(f"private lemma evB_{sid} : {corrected_expr} = B_{sid} := by")
    a(f"  rw [ps_{sid}_{N}]")
    a(f"  norm_num [Block_{sid}, Anti_{sid}, B_{sid}, smulQ, ComplexBall.add, ComplexBall.neg]")
    a("")
    a(f"private lemma hB_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    B_{sid}.contains (∑ n ∈ range ({K} * 5),")
    a("      (dh_coeff n : ℂ) * (n : ℂ) ^ (-s) +")
    a(f"      dhBlock s {K} / 2 - dhAnti s ({K} : ℝ)) := by")
    a(f"  have h := ComplexBall.contains_corrected "
      f"(ComplexBall.contains_dhSumBalls {N} (ht_{sid} hS))")
    a(f"    (ComplexBall.contains_half_of (hBlock_{sid} hS)) (hAnti_{sid} hS)")
    a(f"  rw [evB_{sid}] at h")
    a("  exact h")
    a("")

    slo = F(site["sigma_lo"])
    a(f"theorem enc_{sid} {{s : ℂ}} (hSI : {SI}.contains s) :")
    a(f"    (B_{sid}.inflate {q(tail_r)}).contains (DH s) := by")
    a(f"  have hS := contains_{SB} hSI")
    a("  exact DH_mem_of_partial_enclosure_order2_ball hSI")
    a(f"    (by norm_num [{SI}]) (by norm_num [{SI}])")
    a(f"    (K := {K}) (by norm_num) (hB_{sid} hS)")
    a(f"    (σlo := {q(slo)}) (by norm_num) (by norm_num [{SI}])")
    a(f"    (a := {site['a']}) (b := {site['b']}) (by norm_num) (by norm_num)")
    a(f"    (P := {q(site['P'])}) (by norm_num) (by norm_num)")
    a(f"    (NS := {q(site['NS'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.exact, ZetaLean.Interval.exact])")
    a(f"    (NS1 := {q(site['NS1'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.add, ComplexInterval.exact, ZetaLean.Interval.add,")
    a("      ZetaLean.Interval.exact])")
    a(f"    (NS2 := {q(site['NS2'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.add, ComplexInterval.exact, ZetaLean.Interval.add,")
    a("      ZetaLean.Interval.exact])")
    a(f"    (r := {q(tail_r)}) (by norm_num)")
    a("")

    upper = ball._absc_upper(inflated)
    lower = ball._absc_lower(inflated)
    ball_expr = f"(B_{sid}.inflate {q(tail_r)})"
    if kind == "big":
        M = F(site["M"])
        assert stats["normBound"] <= M
        a(f"theorem upper_{sid} {{s : ℂ}} (hS : {SI}.contains s) :")
        a(f"    ‖DH s‖ ≤ (({q(M)}) : ℝ) := by")
        a(f"  exact norm_le_of_ball_enclosure (enc_{sid} hS)")
        a(f"    {_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    elif kind == "grid":
        beta = F(site["beta"]) if site.get("beta") is not None else beta_literal(stats["normLower"])
        assert stats["normLower"] >= beta
        need = site.get("beta_need")
        assert need is None or beta >= F(need)
        px, py = site["re_lo"], site["im_lo"]
        a(f"noncomputable def z_{sid} : ℂ := ⟨(({q(px)}) : ℝ), (({q(py)}) : ℝ)⟩")
        a(f"theorem beta_{sid} : (({q(beta)}) : ℝ) ≤ ‖DH z_{sid}‖ := by")
        a(f"  have henc := enc_{sid} (s := z_{sid}) (ComplexInterval.contains_exact _ _)")
        a(f"  exact le_norm_of_ball_enclosure henc")
        a(f"    {_lower_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')[1]}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    else:
        eps = F(site["eps"])
        assert stats["normBound"] < eps
        px, py = site["re_lo"], site["im_lo"]
        a(f"noncomputable def z_{sid} : ℂ := ⟨(({q(px)}) : ℝ), (({q(py)}) : ℝ)⟩")
        a(f"theorem centre_lt_{sid} : ‖DH z_{sid}‖ < (({q(eps)}) : ℝ) := by")
        a(f"  have henc := enc_{sid} (s := z_{sid}) (ComplexInterval.contains_exact _ _)")
        a(f"  exact norm_lt_of_ball_enclosure henc")
        a(f"    {_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    a("")
    a("end ZetaLean.DH.Cert")
    a("")
    return "\n".join(lines), stats


def _utf8_len(text: str) -> int:
    return len(text.encode("utf-8"))


def manifest_filename(root: str) -> str:
    return f"{root}.manifest.json"


def _relative_module_path(rel: str) -> str:
    rel = rel.replace("\\", "/")
    path = Path(rel)
    if path.is_absolute() or path.anchor:
        raise ValueError(f"manifest module path must be relative, got {rel!r}")
    parts = path.parts
    if not parts or any(part in (".", "..") for part in parts):
        raise ValueError(f"manifest module path must be relative, got {rel!r}")
    return rel


def _import_names(text: str) -> list[str]:
    names = []
    for line in text.splitlines():
        if line.startswith("import "):
            parts = line.split()
            if len(parts) >= 2:
                names.append(parts[1])
    return names


def _module_name_to_path(name: str) -> str:
    return _relative_module_path(name.replace(".", "/") + ".lean")


def same_site_dep_paths(text: str, root: str) -> list[str]:
    """Same-site import paths, in import order, unique."""
    deps: list[str] = []
    prefix = root + "."
    for name in _import_names(text):
        if name == root or name.startswith(prefix):
            path = _module_name_to_path(name)
            if path not in deps:
                deps.append(path)
    return deps


def site_manifest(
    files: list[tuple[str, str]],
    stats: dict,
) -> dict:
    """Compact per-site compile manifest: relative paths only, no host paths."""
    root = module_root(stats["id"])
    modules = []
    earlier: set[str] = set()
    for rel, text in files:
        rel = _relative_module_path(rel)
        deps = same_site_dep_paths(text, root)
        for dep in deps:
            if dep == rel:
                raise ValueError(f"{rel} imports itself")
            if dep not in earlier:
                raise ValueError(
                    f"{rel} depends on {dep}, which is not an earlier module")
        modules.append({
            "path": rel,
            "bytes": _utf8_len(text),
            "depends": deps,
        })
        earlier.add(rel)
    return {
        "source_format_version": MANIFEST_FORMAT_VERSION,
        "root": root,
        "id": stats["id"],
        "kind": stats["kind"],
        "K": int(stats["K"]),
        "normLower": str(stats["normLower"]),
        "normBound": str(stats["normBound"]),
        "prime_towers": int(stats["prime_towers"]),
        "n_files": len(modules),
        "max_file_bytes": max((m["bytes"] for m in modules), default=0),
        "max_bytes": int(stats["max_bytes"]),
        "sharded": True,
        "modules": modules,
    }


def write_site_manifest(
    outdir: Path,
    files: list[tuple[str, str]],
    stats: dict,
) -> Path:
    payload = site_manifest(files, stats)
    dest = Path(outdir) / manifest_filename(payload["root"])
    dest.write_text(json.dumps(payload, indent=2) + "\n")
    return dest


def _assemble_module(imports: list[str], body: str) -> str:
    header = "\n".join([
        GENERATED_BANNER,
        *[f"import {imp}" for imp in imports],
        "",
        "open Complex Finset ZetaLean ZetaLean.ComplexBall ZetaLean.DH",
        "",
        "set_option maxRecDepth 8000000",
        "set_option maxHeartbeats 40000000",
        "",
        "namespace ZetaLean.DH.Cert",
        "",
    ])
    return header + "\n" + body.rstrip() + "\n\nend ZetaLean.DH.Cert\n"


def _barrel_text(imports: list[str]) -> str:
    return "\n".join([
        GENERATED_BANNER,
        *[f"import {imp}" for imp in imports],
        "",
    ]) + "\n"


def _pack_chunks(
    chunks: list[str],
    *,
    max_bytes: int,
    root: str,
    stem: str,
    first_imports: list[str],
    chain: bool,
) -> tuple[list[tuple[str, str]], str | None]:
    """Pack declaration chunks into importable modules under ``root/stem``.

    One shard becomes ``{root}/{stem}.lean``.  Several shards become numbered
    files plus a barrel module of the same stem.  ``chain`` makes shard *i*
    import shard *i-1* so later composites can see earlier factors.
    """
    if not chunks:
        return [], None

    probe_imports = list(first_imports) + [f"{root}.{stem}00"]
    overhead = _utf8_len(_assemble_module(probe_imports, "")) + 32
    if overhead >= max_bytes:
        raise ValueError(
            f"{root}.{stem} module header is {overhead} bytes, cap is {max_bytes}")
    body_cap = max_bytes - overhead

    for i, chunk in enumerate(chunks):
        assembled = _assemble_module(first_imports, chunk)
        if _utf8_len(assembled) > max_bytes:
            raise ValueError(
                f"{root}.{stem} block {i} is {_utf8_len(assembled)} bytes; "
                f"cap is {max_bytes}")

    groups: list[list[str]] = [[]]
    used = 0
    for chunk in chunks:
        n = _utf8_len(chunk)
        if groups[-1] and used + n > body_cap:
            groups.append([])
            used = 0
        groups[-1].append(chunk)
        used += n

    n_groups = len(groups)
    files: list[tuple[str, str]] = []
    if n_groups == 1:
        mod = f"{root}.{stem}"
        text = _assemble_module(first_imports, "".join(groups[0]))
        if _utf8_len(text) > max_bytes:
            raise ValueError(
                f"{root}/{stem}.lean is {_utf8_len(text)} bytes; cap is {max_bytes}")
        files.append((f"{root}/{stem}.lean", text))
        return files, mod

    width = max(2, len(str(n_groups - 1)))
    names = [f"{root}.{stem}{i:0{width}d}" for i in range(n_groups)]
    for i, group in enumerate(groups):
        imps = [names[i - 1]] if chain and i else list(first_imports)
        rel = f"{root}/{stem}{i:0{width}d}.lean"
        text = _assemble_module(imps, "".join(group))
        if _utf8_len(text) > max_bytes:
            raise ValueError(f"{rel} is {_utf8_len(text)} bytes; cap is {max_bytes}")
        files.append((rel, text))
    files.append((f"{root}/{stem}.lean", _barrel_text(names)))
    return files, f"{root}.{stem}"


def _geometry_block(b: SimpleNamespace, exported: bool) -> str:
    kw = _lemma_kw(exported)
    SI, SB = b.SI, b.SB
    lines = [
        f"def {SI} : ComplexInterval :=",
        f"  ⟨⟨{q(b.relo)}, {q(b.rehi)}, by norm_num⟩, ⟨{q(b.imlo)}, {q(b.imhi)}, by norm_num⟩⟩",
        "",
        f"def {SB} : ComplexBall := {lit(b.Sval)}",
        "",
        f"{kw} contains_{SB} {{s : ℂ}} (hS : {SI}.contains s) : {SB}.contains s := by",
        f"  have h := ComplexBall.contains_ofInterval (B := {SI}) (hw := {q(b.half_width)}) hS",
        f"    (by norm_num [{SI}]) (by norm_num)",
        f"  convert h using 1 <;> norm_num [{SB}, {SI}, ComplexBall.ofInterval]",
        "",
    ]
    return "\n".join(lines) + "\n"


def _pow_block(b: SimpleNamespace, m: int, exported: bool) -> str:
    kw = _lemma_kw(exported)
    sid, SB = b.sid, b.SB
    name = f"Pow_{sid}_{m}"
    value = b.pow_values[m]
    mode = b.pow_kind[m]
    lines: list[str] = [f"def {name} : ComplexBall := {lit(value)}"]
    a = lines.append
    if mode[0] == "one":
        a(f"{kw} hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
        a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
        a("  have h := ComplexBall.contains_exact (1 : ℚ) (0 : ℚ)")
        a("  rw [show (⟨((1 : ℚ) : ℝ), ((0 : ℚ) : ℝ)⟩ : ℂ) = (1 : ℂ) by")
        a("    apply Complex.ext <;> norm_num] at h")
        a(f"  simpa [{name}, ComplexBall.exact] using h")
    elif mode[0] == "prime":
        a(f"{kw} hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
        a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
        a(f"  have hSp : Prime_{m}.S.contains s := by")
        a(f"    simpa [Prime_{m}.S, {SB}] using hS")
        a(f"  have h := Prime_{m}.pilot_contains_cpow hSp")
        a(f"  simpa [{name}, Prime_{m}.Sq_{KE}] using h")
    else:
        _, left, right = mode
        left_name, right_name = f"Pow_{sid}_{left}", f"Pow_{sid}_{right}"
        ul = ball._absc_upper(b.pow_values[left])
        ur = ball._absc_upper(b.pow_values[right])
        a(f"{kw} evpow_{sid}_{m} :")
        a(f"    coarsenB {P} (ComplexBall.mul {left_name} {right_name} {q(ul)} {q(ur)}) =")
        a(f"      {name} := by")
        a(f"  norm_num [{left_name}, {right_name}, {name}, coarsenB, recentre, widenRad,")
        a("    ceilP, ComplexBall.mul]")
        a(f"{kw} hp_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
        a(f"    {name}.contains ((({m} : ℕ) : ℂ) ^ (-s)) := by")
        a(f"  have h := contains_cpow_mulB_coarsen_lit {P}")
        a(f"    {_norm_proof(left_name, b.pow_values[left], left_name)}")
        a(f"    {_norm_proof(right_name, b.pow_values[right], right_name)}")
        a(f"    (hp_{sid}_{left} hS) (hp_{sid}_{right} hS)")
        a(f"  rw [evpow_{sid}_{m}] at h")
        a("  simpa using h")
    a("")
    return "\n".join(lines) + "\n"


def _prime_block(b: SimpleNamespace, prime: int, exported: bool) -> str:
    return b.prime_fragments[prime].rstrip() + "\n\n" + _pow_block(b, prime, exported)


def _term_block(b: SimpleNamespace, m: int, exported: bool) -> str:
    kw = _lemma_kw(exported)
    sid, SB = b.sid, b.SB
    tname = f"Term_{sid}_{m}"
    kappa_simp = (
        "coeffBall, kappaBall, ofRealInterval, DH.kappaI, ComplexBall.exact, "
        "ComplexBall.neg")
    lines: list[str] = [f"def {tname} : ComplexBall := {lit(b.term_values[m])}"]
    a = lines.append
    if m % 5 == 0:
        a(f"{kw} hterm_{sid}_{m} {{s : ℂ}} :")
        a(f"    {tname}.contains ((dh_coeff {m} : ℂ) * (({m} : ℕ) : ℂ) ^ (-s)) := by")
        a(f"  simpa [{tname}, ComplexBall.exact] using "
          f"(ComplexBall.contains_coeff_term_zero (s := s) {m} (by norm_num [dh_coeff]))")
    else:
        pname = f"Pow_{sid}_{m}"
        uc = ball._absc_upper(ball.coeffBox(m))
        up = ball._absc_upper(b.pow_values[m])
        a(f"{kw} evterm_{sid}_{m} :")
        a(f"    ComplexBall.mul (coeffBall {m}) {pname} {q(uc)} {q(up)} = {tname} := by")
        a(f"  norm_num [{pname}, {tname}, {kappa_simp}, ComplexBall.mul]")
        a(f"{kw} hterm_{sid}_{m} {{s : ℂ}} (hS : {SB}.contains s) :")
        a(f"    {tname}.contains ((dh_coeff {m} : ℂ) * (({m} : ℕ) : ℂ) ^ (-s)) := by")
        a(f"  have h := ComplexBall.contains_coeff_term_ne {m} (by norm_num)")
        a(f"    {_norm_proof(f'(coeffBall {m})', ball.coeffBox(m), kappa_simp)}")
        a(f"    {_norm_proof(pname, b.pow_values[m], pname)} (hp_{sid}_{m} hS)")
        a(f"  rw [evterm_{sid}_{m}] at h")
        a("  exact h")
    a("")
    return "\n".join(lines) + "\n"


def _termfun_ht_block(b: SimpleNamespace, exported: bool) -> str:
    kw = _lemma_kw(exported)
    sid, SB, N = b.sid, b.SB, b.N
    lines: list[str] = [f"def term_{sid} : ℕ → ComplexBall"]
    a = lines.append
    for m in range(N):
        a(f"  | {m} => Term_{sid}_{m}")
    a("  | _ => ComplexBall.exact 0 0")
    a("")
    for m in range(N):
        a(f"{kw} evfun_{sid}_{m} : term_{sid} {m} = Term_{sid}_{m} := rfl")
    a("")
    a(f"{kw} ht_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    ∀ m, m < {N} → (term_{sid} m).contains")
    a("      ((dh_coeff m : ℂ) * (m : ℂ) ^ (-s)) :=")
    a("  fun m hm =>")
    a("    match m, hm with")
    for m in range(N):
        suffix = "" if m % 5 == 0 else " hS"
        a(f"    | {m}, _ => by simpa [evfun_{sid}_{m}] using hterm_{sid}_{m}{suffix}")
    a(f"    | (n + {N}), hm => absurd hm (by omega)")
    a("")
    return "\n".join(lines) + "\n"


def _partial_blocks(b: SimpleNamespace, exported: bool) -> list[str]:
    kw = _lemma_kw(exported)
    sid, N = b.sid, b.N
    bounds = sorted(set(list(range(0, N, CHUNK)) + [N]))
    blocks = [
        f"{kw} ps_{sid}_0 : dhSumBalls (term_{sid}) 0 = {lit(b.partial[0])} := rfl\n\n"
    ]
    for lo, hi in zip(bounds, bounds[1:]):
        rws: list[str] = []
        for n in range(hi, lo, -1):
            rws.extend((f"show ({n} : ℕ) = {n - 1} + 1 from rfl", "dhSumBalls_succ"))
        rws.append(f"ps_{sid}_{lo}")
        rws.extend(f"evfun_{sid}_{n}" for n in range(lo, hi))
        term_defs = ", ".join(f"Term_{sid}_{n}" for n in range(lo, hi))
        lines = [
            f"{kw} ps_{sid}_{hi} : dhSumBalls (term_{sid}) {hi} =",
            f"    {lit(b.partial[hi])} := by",
            "  rw [" + ",\n    ".join(rws) + "]",
            f"  norm_num [{term_defs}, ComplexBall.add]",
            "",
        ]
        blocks.append("\n".join(lines) + "\n")
    return blocks


def _assembly_block(b: SimpleNamespace) -> str:
    """Block, anti-term, corrected ball, and the site theorem.  Lives in the root."""
    site, kind, sid = b.site, b.kind, b.sid
    K, N, SI, SB = b.K, b.N, b.SI, b.SB
    tail_r, stats = b.tail_r, b.stats
    m1, m2, m3, m4 = b.m1, b.m2, b.m3, b.m4
    pair, block = b.pair, b.block
    five_one_sub, anti_v = b.five_one_sub, b.anti_v
    anti_pair, anti_sum, anti = b.anti_pair, b.anti_sum, b.anti
    corrected, inflated = b.corrected, b.inflated
    lines: list[str] = []
    a = lines.append
    pnames = {m: f"Pow_{sid}_{m}" for m in (m1, m2, m3, m4)}
    pair_expr = f"({pnames[m2]}.add {pnames[m3]}.neg)"
    uk, upair = ball._absc_upper(ball.KAPPA_C), ball._absc_upper(pair)
    block_expr = (
        f"(({pnames[m1]}.add {pnames[m4]}.neg).add "
        f"(ComplexBall.mul kappaBall {pair_expr} {q(uk)} {q(upair)}))")
    a(f"def Block_{sid} : ComplexBall := {lit(block)}")
    a(f"private lemma evblock_{sid} : {block_expr} = Block_{sid} := by")
    a(f"  norm_num [{', '.join(pnames.values())}, Block_{sid}, kappaBall, ofRealInterval,")
    a("    DH.kappaI, ComplexBall.add, ComplexBall.neg, ComplexBall.mul]")
    a("")

    one_minus = ball.cadd(ball.cexact(1, 0), ball.cneg(b.Sval))
    u_one_minus = ball._absc_upper(one_minus)
    lower5, lower5proof = _lower_norm_proof(
        f"(fiveOneSubBall {SB} {q(u_one_minus)})", five_one_sub,
        f"{SB}, fiveOneSubBall, ComplexBall.exact, ComplexBall.add, ComplexBall.neg, ComplexBall.mul")
    a(f"def AntiV_{sid} : ComplexBall := {lit(anti_v)}")
    a(f"private lemma evV_{sid} :")
    a(f"    (fiveOneSubBall {SB} {q(u_one_minus)}).inv {q(anti_v.rad)} = AntiV_{sid} := by")
    a(f"  norm_num [{SB}, AntiV_{sid}, fiveOneSubBall, ComplexBall.exact, ComplexBall.add,")
    a("    ComplexBall.neg, ComplexBall.mul, ComplexBall.inv]")
    a("")
    a(f"private lemma hV_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    AntiV_{sid}.contains ((5 * (1 - s))⁻¹) := by")
    a(f"  have h := contains_inv5sBall (u := {q(u_one_minus)}) (l := {q(lower5)})")
    a(f"    (R := {q(anti_v.rad)}) hS")
    a(f"    {_norm_proof(f'((ComplexBall.exact 1 0).add {SB}.neg)', one_minus, f'{SB}, ComplexBall.exact, ComplexBall.add, ComplexBall.neg')}")
    a("    (by norm_num)")
    a(f"    {lower5proof} (by norm_num [fiveOneSubBall, {SB}, ComplexBall.exact,")
    a("      ComplexBall.add, ComplexBall.neg, ComplexBall.mul])")
    a(f"    (by norm_num [fiveOneSubBall, {SB}, ComplexBall.exact, ComplexBall.add,")
    a("      ComplexBall.neg, ComplexBall.mul])")
    a(f"  rw [evV_{sid}] at h")
    a("  exact h")
    a("")

    qm1 = f"({K} * 5 + 1 : ℚ)"
    qm2 = f"({K} * 5 + 2 : ℚ)"
    qm3 = f"({K} * 5 + 3 : ℚ)"
    qm4 = f"({K} * 5 + 4 : ℚ)"
    anti_pair_expr = (
        f"((smulQ {qm2} {pnames[m2]}).add "
        f"(smulQ {qm3} {pnames[m3]}).neg)")
    uapair = ball._absc_upper(anti_pair)
    anti_sum_expr = (
        f"(((smulQ {qm1} {pnames[m1]}).add "
        f"(smulQ {qm4} {pnames[m4]}).neg).add "
        f"(ComplexBall.mul kappaBall {anti_pair_expr} {q(uk)} {q(uapair)}))")
    usum, uv = ball._absc_upper(anti_sum), ball._absc_upper(anti_v)
    anti_expr = f"(ComplexBall.mul {anti_sum_expr} AntiV_{sid} {q(usum)} {q(uv)})"
    a(f"def Anti_{sid} : ComplexBall := {lit(anti)}")
    a(f"private lemma evanti_{sid} : {anti_expr} = Anti_{sid} := by")
    a(f"  norm_num [{', '.join(pnames.values())}, AntiV_{sid}, Anti_{sid}, kappaBall,")
    a("    ofRealInterval, DH.kappaI, smulQ, ComplexBall.add, ComplexBall.neg, ComplexBall.mul]")
    a("")

    correction_simp = (
        f"{', '.join(pnames.values())}, kappaBall, ofRealInterval, DH.kappaI, "
        "smulQ, ComplexBall.add, ComplexBall.neg, ComplexBall.mul")
    a(f"private lemma hBlock_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    Block_{sid}.contains (dhBlock s {K}) := by")
    a(f"  have h := contains_dhBlock_of_terms_ball (s := s) {K}")
    for m in (m1, m2, m3, m4):
        a(f"    (hp_{sid}_{m} hS)")
    a(f"    {_norm_proof('kappaBall', ball.KAPPA_C, 'kappaBall, ofRealInterval, DH.kappaI')}")
    a(f"    {_norm_proof(pair_expr, pair, correction_simp)}")
    a(f"  rw [evblock_{sid}] at h")
    a("  exact h")
    a("")
    a(f"private lemma hAnti_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    Anti_{sid}.contains (dhAnti s ({K} : ℝ)) := by")
    a(f"  have h := contains_dhAnti_of_terms_ball (s := s) {K}")
    for m in (m1, m2, m3, m4):
        a(f"    (hp_{sid}_{m} hS)")
    a(f"    (hV_{sid} hS)")
    a(f"    {_norm_proof('kappaBall', ball.KAPPA_C, 'kappaBall, ofRealInterval, DH.kappaI')}")
    a(f"    {_norm_proof(anti_pair_expr, anti_pair, correction_simp)}")
    a(f"    {_norm_proof(anti_sum_expr, anti_sum, correction_simp)}")
    a(f"    {_norm_proof(f'AntiV_{sid}', anti_v, f'AntiV_{sid}')}")
    a("  norm_num at h")
    a(f"  have hev := evanti_{sid}")
    a("  norm_num at hev")
    a("  rw [hev] at h")
    a("  exact h")
    a("")

    a(f"def B_{sid} : ComplexBall := {lit(corrected)}")
    corrected_expr = (
        f"((dhSumBalls (term_{sid}) {N}).add (smulQ (1/2 : ℚ) Block_{sid})).add "
        f"Anti_{sid}.neg"
    )
    a(f"private lemma evB_{sid} : {corrected_expr} = B_{sid} := by")
    a(f"  rw [ps_{sid}_{N}]")
    a(f"  norm_num [Block_{sid}, Anti_{sid}, B_{sid}, smulQ, ComplexBall.add, ComplexBall.neg]")
    a("")
    a(f"private lemma hB_{sid} {{s : ℂ}} (hS : {SB}.contains s) :")
    a(f"    B_{sid}.contains (∑ n ∈ range ({K} * 5),")
    a("      (dh_coeff n : ℂ) * (n : ℂ) ^ (-s) +")
    a(f"      dhBlock s {K} / 2 - dhAnti s ({K} : ℝ)) := by")
    a(f"  have h := ComplexBall.contains_corrected "
      f"(ComplexBall.contains_dhSumBalls {N} (ht_{sid} hS))")
    a(f"    (ComplexBall.contains_half_of (hBlock_{sid} hS)) (hAnti_{sid} hS)")
    a(f"  rw [evB_{sid}] at h")
    a("  exact h")
    a("")

    slo = F(site["sigma_lo"])
    a(f"theorem enc_{sid} {{s : ℂ}} (hSI : {SI}.contains s) :")
    a(f"    (B_{sid}.inflate {q(tail_r)}).contains (DH s) := by")
    a(f"  have hS := contains_{SB} hSI")
    a("  exact DH_mem_of_partial_enclosure_order2_ball hSI")
    a(f"    (by norm_num [{SI}]) (by norm_num [{SI}])")
    a(f"    (K := {K}) (by norm_num) (hB_{sid} hS)")
    a(f"    (σlo := {q(slo)}) (by norm_num) (by norm_num [{SI}])")
    a(f"    (a := {site['a']}) (b := {site['b']}) (by norm_num) (by norm_num)")
    a(f"    (P := {q(site['P'])}) (by norm_num) (by norm_num)")
    a(f"    (NS := {q(site['NS'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.exact, ZetaLean.Interval.exact])")
    a(f"    (NS1 := {q(site['NS1'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.add, ComplexInterval.exact, ZetaLean.Interval.add,")
    a("      ZetaLean.Interval.exact])")
    a(f"    (NS2 := {q(site['NS2'])}) (by norm_num [{SI}, ComplexInterval.normBound,")
    a("      ComplexInterval.add, ComplexInterval.exact, ZetaLean.Interval.add,")
    a("      ZetaLean.Interval.exact])")
    a(f"    (r := {q(tail_r)}) (by norm_num)")
    a("")

    ball_expr = f"(B_{sid}.inflate {q(tail_r)})"
    if kind == "big":
        M = F(site["M"])
        assert stats["normBound"] <= M
        a(f"theorem upper_{sid} {{s : ℂ}} (hS : {SI}.contains s) :")
        a(f"    ‖DH s‖ ≤ (({q(M)}) : ℝ) := by")
        a(f"  exact norm_le_of_ball_enclosure (enc_{sid} hS)")
        a(f"    {_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    elif kind == "grid":
        beta = F(site["beta"]) if site.get("beta") is not None else beta_literal(stats["normLower"])
        assert stats["normLower"] >= beta
        need = site.get("beta_need")
        assert need is None or beta >= F(need)
        px, py = site["re_lo"], site["im_lo"]
        a(f"noncomputable def z_{sid} : ℂ := ⟨(({q(px)}) : ℝ), (({q(py)}) : ℝ)⟩")
        a(f"theorem beta_{sid} : (({q(beta)}) : ℝ) ≤ ‖DH z_{sid}‖ := by")
        a(f"  have henc := enc_{sid} (s := z_{sid}) (ComplexInterval.contains_exact _ _)")
        a(f"  exact le_norm_of_ball_enclosure henc")
        a(f"    {_lower_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')[1]}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    else:
        eps = F(site["eps"])
        assert stats["normBound"] < eps
        px, py = site["re_lo"], site["im_lo"]
        a(f"noncomputable def z_{sid} : ℂ := ⟨(({q(px)}) : ℝ), (({q(py)}) : ℝ)⟩")
        a(f"theorem centre_lt_{sid} : ‖DH z_{sid}‖ < (({q(eps)}) : ℝ) := by")
        a(f"  have henc := enc_{sid} (s := z_{sid}) (ComplexInterval.contains_exact _ _)")
        a(f"  exact norm_lt_of_ball_enclosure henc")
        a(f"    {_norm_proof(ball_expr, inflated, f'B_{sid}, ComplexBall.inflate')}")
        a(f"    (by norm_num [B_{sid}, ComplexBall.inflate])")
    a("")
    return "\n".join(lines) + "\n"


def emit_site_ball_modules(
    site: dict,
    kind: str,
    *,
    max_bytes: int = MAX_SHARD_BYTES,
) -> tuple[list[tuple[str, str]], dict]:
    """Emit one site as importable Lean modules with a size cap per file.

    The last pair is the root ``C{id}.lean`` carrying the existing site theorem.
    Prime towers and composite ``Pow`` declarations live in sibling modules so
    a large site never materialises as one 100 MB file.
    """
    if max_bytes <= 0:
        raise ValueError("max_bytes must be positive")
    b = _prepare_site(site, kind)
    root = module_root(b.sid)
    files: list[tuple[str, str]] = []

    base_body = _geometry_block(b, exported=True)
    if 1 in b.pow_values:
        base_body += _pow_block(b, 1, exported=True)
    base_mod = f"{root}.Base"
    base_text = _assemble_module(["ZetaLean.BallCertSupport"], base_body)
    if _utf8_len(base_text) > max_bytes:
        raise ValueError(
            f"{root}/Base.lean is {_utf8_len(base_text)} bytes; cap is {max_bytes}")
    files.append((f"{root}/Base.lean", base_text))

    prime_chunks = [
        _prime_block(b, p, exported=True) for p in sorted(b.prime_fragments)]
    p_files, p_mod = _pack_chunks(
        prime_chunks, max_bytes=max_bytes, root=root, stem="Primes",
        first_imports=[base_mod], chain=False)
    files.extend(p_files)
    if p_mod is None:
        raise ValueError(f"{b.sid} produced no prime towers")

    comp_chunks = [
        _pow_block(b, m, exported=True)
        for m in b.pow_order
        if b.pow_kind[m][0] == "composite"
    ]
    c_files, c_mod = _pack_chunks(
        comp_chunks, max_bytes=max_bytes, root=root, stem="Composites",
        first_imports=[p_mod], chain=True)
    files.extend(c_files)
    last = c_mod or p_mod

    term_chunks = [_term_block(b, m, exported=True) for m in range(b.N)]
    t_files, t_mod = _pack_chunks(
        term_chunks, max_bytes=max_bytes, root=root, stem="Terms",
        first_imports=[last], chain=False)
    files.extend(t_files)
    last = t_mod or last

    termfun = _termfun_ht_block(b, exported=True)
    partials = _partial_blocks(b, exported=True)
    assembly = _assembly_block(b)
    tail = termfun + "".join(partials) + assembly
    root_text = _assemble_module([last], tail)
    if _utf8_len(root_text) <= max_bytes:
        files.append((f"{root}.lean", root_text))
    else:
        s_files, s_mod = _pack_chunks(
            [termfun, *partials], max_bytes=max_bytes, root=root, stem="Sums",
            first_imports=[last], chain=True)
        files.extend(s_files)
        last = s_mod or last
        root_text = _assemble_module([last], assembly)
        if _utf8_len(root_text) > max_bytes:
            raise ValueError(
                f"{root}.lean is {_utf8_len(root_text)} bytes; cap is {max_bytes}")
        files.append((f"{root}.lean", root_text))

    sizes = [_utf8_len(text) for _, text in files]
    stats = dict(b.stats)
    stats.update({
        "modules": [rel for rel, _ in files],
        "file_bytes": sizes,
        "max_file_bytes": max(sizes) if sizes else 0,
        "n_files": len(files),
        "sharded": True,
        "max_bytes": max_bytes,
    })
    stats["manifest"] = site_manifest(files, stats)
    return files, stats
