#!/usr/bin/env python3
"""Theorems with price tags: the receipts ledger.

Aggregates ONLY data already committed to this public repository — the
telemetry run records (telemetry/runs/*.jsonl) and hunt handbacks
(hunts/*/HANDBACK.json) — into one page: what was proved, by which run,
at what measured cost, under which controls. No field is inferred; a run
that did not report a number shows an absent number ("absent, not zero").

The page this emits makes the lab's stated objective — valuable research
output per unit input — publicly auditable per result. To our knowledge
no laboratory publishes cost-per-theorem provenance; the honest version
of the claim everyone else makes in prose.

Usage: python3 scripts/make_receipts.py [-o docs/receipts.md]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _runs() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for f in sorted((ROOT / "telemetry" / "runs").glob("*.jsonl")):
        rec: dict = {"run_id": f.stem}
        for line in f.read_text(encoding="utf-8").splitlines():
            try:
                d = json.loads(line)
            except ValueError:
                continue
            for k in ("model", "task", "task_ref", "tokens",
                      "duration_seconds", "status", "started_at",
                      "finished_at"):
                if d.get(k) is not None:
                    rec[k] = d[k]
        out[f.stem] = rec
    return out


def _handbacks() -> list[dict]:
    out = []
    for f in sorted(ROOT.glob("hunts/*/HANDBACK.json")):
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
        except ValueError:
            continue
        d["_hunt"] = f.parent.name
        out.append(d)
    return out


def _fmt_tokens(t: dict | None) -> str:
    if not isinstance(t, dict) or not t:
        return "absent (not zero)"
    parts = []
    for k in ("input", "output", "cache_read", "cache_creation"):
        if k in t:
            parts.append(f"{k} {t[k]:,}")
    return ", ".join(parts) or "absent (not zero)"


def build() -> str:
    runs = _runs()
    lines = [
        "# Receipts — every settled run, with its price tag",
        "",
        "Generated by `scripts/make_receipts.py` from the committed",
        "telemetry and handbacks; nothing here is typed in by hand.",
        "A missing number means the run did not report one — absent, not",
        "zero. Grades and caveats live in each hunt's own RESULTS; this",
        "page is the cost-and-conclusion index.",
        "",
    ]
    for hb in _handbacks():
        rid = hb.get("run_id", "")
        rec = runs.get(rid, {})
        lines += [
            f"## {hb['_hunt']} — run `{rid[:8] or 'unrecorded'}`",
            "",
            f"**Status:** {hb.get('status', 'unrecorded')}",
            "",
            f"**Conclusion:** {hb.get('conclusion', 'unrecorded')}",
            "",
            f"* model: {rec.get('model', 'undeclared')}",
            f"* tokens: {_fmt_tokens(rec.get('tokens'))}",
            f"* duration: "
            + (f"{rec['duration_seconds']} s" if rec.get("duration_seconds")
               else "absent"),
            f"* threads left for the next run: {len(hb.get('threads', []))};"
            f" reusable-capability proposals: {len(hb.get('core_candidates', []))}",
            "",
        ]
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default=None)
    a = ap.parse_args()
    text = build()
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
        print(f"wrote {a.out} ({len(text.splitlines())} lines)")
    else:
        print(text)
