"""Generate ZetaLean/OracleDH.lean: oracle enclosures for Dirichlet terms.

The Oracle Boundary Pattern, stated honestly.  This script computes each
Dirichlet term n^{-s} at the Davenport-Heilbronn off-line zero with mpmath at
high working precision, then rounds OUTWARD by an explicit slack (1e-50, far
above the ~1e-68 rounding error of dps=70 arithmetic), and emits each
enclosure as a `ComplexInterval` with exact rational endpoints.

Division of labour, matching `zeta/rigor.py`'s vocabulary:

* The numbers below are ORACLE CLAIMS: floating point plus outward rounding,
  not enclosure-carrying arithmetic.  Nothing in Lean certifies them.
* What Lean certifies is everything from the `ComplexInterval` layer upward:
  the interval operations in `ZetaLean/Rigor.lean` and the partial-sum glue
  in `ZetaLean/DirichletEval.lean` are kernel-checked, so IF each claim
  contains its term, THEN the folded sum contains the partial sum.

Closing the IF is the open mountain of Rung 3 Phase B (certified exp/log in
Lean, plus a tail bound for the analytic continuation -- see the note at the
bottom of the generated file).

Run from `lean/`:  ../.venv/bin/python oracle_dh.py
"""

from fractions import Fraction

from mpmath import mp

# Working precision: well beyond the emitted slack of 1e-50.
mp.dps = 70

# Outward-rounding slack per endpoint.
SLACK = Fraction(1, 10**50)

# The off-line zero of the Davenport-Heilbronn function (docs/11; the same
# point `zeta/epstein.py` measures).  Exact rationals, mirrored into Lean.
SIGMA = Fraction(808517, 1000000)
TAU = Fraction(85699348, 1000000)

N_TERMS = 5


def mpf_to_fraction(x) -> Fraction:
    """Exact value of an mpmath float as a Fraction (no rounding)."""
    sign, man, exp, _ = x._mpf_
    if man == 0:
        return Fraction(0)
    frac = Fraction(man, 1) * Fraction(2) ** exp
    return -frac if sign else frac


def interval_fields(value) -> tuple[Fraction, Fraction]:
    """Outward-rounded rational endpoints around an mpmath float."""
    center = mpf_to_fraction(value)
    return center - SLACK, center + SLACK


def lean_interval(lo: Fraction, hi: Fraction, indent: str) -> str:
    # Continuation fields must align with the first field (`lo`): Lean 4
    # structure instances are whitespace-sensitive, and a field starting to
    # the left of the first one ends the literal.
    return (
        f"{{ lo := {lo.numerator} / {lo.denominator},\n"
        f"{indent}hi := {hi.numerator} / {hi.denominator},\n"
        f"{indent}le := by norm_num }}"
    )


def generate_lean_certificate() -> None:
    s = mp.mpc(mp.mpf(SIGMA.numerator) / SIGMA.denominator,
               mp.mpf(TAU.numerator) / TAU.denominator)

    lean_code = f"""import Mathlib
import ZetaLean.Rigor
import ZetaLean.DirichletEval

/-!
# Davenport-Heilbronn Oracle Certificate

Generated by `lean/oracle_dh.py`; do not edit by hand.

Each `term_n_bound` is an ORACLE CLAIM for `n^{{-s}}` at the off-line zero
`s = offline_zero_re + offline_zero_im * I`: mpmath at 70 digits, rounded
outward by 1e-50 per endpoint, endpoints exact rationals.  Nothing here is
kernel-checked about `n^{{-s}}` itself; what the kernel checks is the interval
arithmetic consuming these claims (`ZetaLean/Rigor.lean`,
`ZetaLean/DirichletEval.lean`).  Closing that gap is Rung 3 Phase B.
-/

def offline_zero_re : ℚ := {SIGMA.numerator} / {SIGMA.denominator}
def offline_zero_im : ℚ := {TAU.numerator} / {TAU.denominator}
"""

    for n in range(1, N_TERMS + 1):
        term = mp.power(n, -s)
        re_lo, re_hi = interval_fields(term.real)
        im_lo, im_hi = interval_fields(term.imag)
        lean_code += f"""
def term_{n}_bound : ZetaLean.ComplexInterval :=
  {{ re := {lean_interval(re_lo, re_hi, " " * 12)},
    im := {lean_interval(im_lo, im_hi, " " * 12)} }}
"""

    lean_code += """
/-
Note: the Dirichlet series for DH(s) does not converge absolutely at
Re(s) ≈ 0.808, so no partial sum of these terms approximates DH at the
off-line zero.  Rigorous evaluation must go through the Hurwitz zeta
expansion or another route to the analytic continuation, with a certified
tail bound.  The bounds above are for the individual terms n^{-s} only.
-/
"""

    with open("ZetaLean/OracleDH.lean", "w") as f:
        f.write(lean_code)

    print(f"Certificate generated in ZetaLean/OracleDH.lean "
          f"({N_TERMS} terms, slack {float(SLACK):.0e} per endpoint)")


if __name__ == "__main__":
    generate_lean_certificate()
