import sys
from fractions import Fraction
import mpmath
from mpmath import iv, mp

# Set high precision for the oracle
mp.dps = 50
iv.prec = 128

def generate_lean_certificate():
    sigma = Fraction(808517, 1000000)
    tau = Fraction(85699348, 1000000)
    s = mp.mpc(float(sigma), float(tau))
    
    lean_code = f"""import Mathlib
import ZetaLean.Rigor
import ZetaLean.DirichletEval

/-!
# Davenport-Heilbronn Oracle Certificate
This file is generated by `oracle_dh.py`.
It provides the certified bounds for the Davenport-Heilbronn function at the off-line zero.
-/

def offline_zero_re : ℚ := {sigma.numerator} / {sigma.denominator}
def offline_zero_im : ℚ := {tau.numerator} / {tau.denominator}

"""
    # Evaluate first few terms n^(-s) = exp(-s * log(n))
    for n in range(1, 6):
        x = -s * mp.log(n)
        
        # Choose k such that |x / 2^k| <= 1
        x_mag = abs(x)
        k = 0
        while x_mag / (2**k) > 0.9:
            k += 1
            
        x_scaled = x / (2**k)
        
        # Compute Taylor polynomial of degree N=15
        N = 15
        T = mp.mpc(0)
        term = mp.mpc(1)
        for m in range(N):
            T += term
            term = term * x_scaled / (m + 1)
            
        # Error bound for exp(x_scaled)
        x_scaled_mag = abs(x_scaled)
        eps = (x_scaled_mag**N) * (N + 1) / (mp.fac(N) * N)
        
        # Now square the disk k times
        # A disk is center C, radius R
        C = T
        R = eps
        for _ in range(k):
            # (C + r)^2 = C^2 + 2Cr + r^2
            # Max magnitude of error is 2|C|R + R^2
            new_C = C**2
            new_R = 2 * abs(C) * R + R**2
            C = new_C
            R = new_R
            
        re_val = C.real
        im_val = C.imag
        
        re_lb = re_val - R
        re_ub = re_val + R
        im_lb = im_val - R
        im_ub = im_val + R
        
        lean_code += f"""
def term_{n}_bound : BoundedComplex :=
  {{ re_lb := {re_lb},
    re_ub := {re_ub},
    im_lb := {im_lb},
    im_ub := {im_ub},
    re_lb_le_ub := by norm_num,
    im_lb_le_ub := by norm_num }}
"""
    
    with open("ZetaLean/OracleDH.lean", "w") as f:
        f.write(lean_code)
    
    print("Certificate generated in ZetaLean/OracleDH.lean")

if __name__ == "__main__":
    generate_lean_certificate()
