"""Checks for the explicit witness bounds of RESULTS.md.

Each test pins a load-bearing step: the Arb constants against mpmath and a
functional-equation route, the closed-form margins, the small-modulus
generation table, the combinatorial sieve inequality, the Miller subgroup
lemma, the exponent response to a weakened abscissa, and a planted fault that
the record table must refute.
"""

from __future__ import annotations

import json
import math
from fractions import Fraction as F
from math import gcd
from pathlib import Path

import mpmath as mp
import numpy as np
import pytest
from flint import arb

from hunts.qrh_nonresidue import explicit as E
from hunts.qrh_nonresidue import tables as T

HERE = Path(__file__).resolve().parent


@pytest.fixture(scope="module")
def C():
    return E.constants(F(7, 8), F(1, 4))


def _lo(b):
    return float(b.lower())


def test_backend_is_arb():
    from zeta import rigor
    assert rigor.BACKEND == "python-flint"


def test_constants_match_mpmath_and_functional_equation(C):
    with mp.workdps(40):
        c = mp.mpf(1) / 4
        s0 = mp.mpf(2)
        lz = mp.zeta(s0, derivative=1) / mp.zeta(s0)
        A_chi = -lz - mp.log(mp.pi) / 2 + mp.digamma((s0 + 1) / 2) / 2
        A_zeta = 1 / s0 + 1 / (s0 - 1) - mp.log(mp.pi) / 2 + mp.digamma(s0 / 2) / 2 + lz
        lz1 = mp.zeta(1 + c, derivative=1) / mp.zeta(1 + c)
        fe = -lz1 + mp.log(mp.pi) - mp.digamma(-c / 2) / 2 - mp.digamma((1 + c) / 2) / 2
    assert C.A_chi.contains(arb(mp.nstr(A_chi, 30))) or abs(float(C.A_chi.mid()) - float(A_chi)) < 1e-14
    assert abs(float(C.A_zeta.mid()) - float(A_zeta)) < 1e-14
    # -zeta'/zeta(-c) from Arb's continuation versus the functional equation
    assert abs(float(C.Fz.mid()) + float(fe)) < 1e-14
    # sum over zeta zeros of Re 1/(2 - rho) is positive and small
    assert 0.06 < float(C.A_zeta.mid()) < 0.08


def test_K_of_x_constant_regime_and_grid_bound(C):
    big = E.K_of_x(C, arb(6))
    assert big.overlaps(1 / (arb(7) / 8 + arb(1) / 4))
    small = E.K_of_x(C, arb(2))
    # below L_star the zeros near Re s = 1/8 dominate and K grows
    assert _lo(small) > _lo(big)
    # brute check of the supremum at log x = 2
    b = np.linspace(1 / 8, 7 / 8, 20001)
    f = np.exp((b - 7 / 8) * 2) * (2 - b) / (b + 0.25) ** 2
    assert f.max() <= float(small.upper())


def test_theorem1_closed_margin_positive_at_L0(C):
    L0 = arb(5) / 2
    m = E.margin_closed(C, L0)
    assert _lo(m) > 0.09
    assert (8 * L0.log()) >= C.L_star
    # control: the margin is nondecreasing on a grid beyond L0, as the proof claims
    vals = [_lo(E.margin_closed(C, arb(L))) for L in (2.5, 3, 4, 6, 10, 30, 100, 1000)]
    assert all(b >= a for a, b in zip(vals, vals[1:]))
    # and it is negative just below, so L0 is not padded
    assert _lo(E.margin_closed(C, arb(2))) < 0


def test_theorem1b_margin(C):
    Cb = E.constants(F(7, 8), F(1, 8))
    m = E.margin_closed(Cb, arb(6), arb(7) / 10)
    assert _lo(m) > 0
    assert (8 * (arb(7) / 10 * 6).log()) >= Cb.L_star


def test_small_moduli_generation_bound():
    primes = [int(p) for p in np.nonzero(T.prime_sieve(2000))[0]]
    known = {3: 2, 4: 3, 5: 2, 6: 5, 7: 3, 8: 5, 9: 2, 10: 3, 11: 2, 12: 7, 24: 13}
    for q, N in known.items():
        assert T.generation_bound(q, primes) == N
    worst = max(T.generation_bound(q, primes) / T.log8(q) for q in range(3, 400))
    assert 0.94 < worst <= 1  # attained at q = 3: n = 2 against (log 3)^8 = 2.122


def test_generation_bound_equals_max_character_nonresidue():
    """Lemma 6 by brute force: characters of (Z/qZ)^* via a discrete log basis."""
    for q in (15, 16, 21, 35, 40):
        units = [a for a in range(1, q) if gcd(a, q) == 1]
        primes = [p for p in range(2, 200) if all(p % d for d in range(2, p))]
        N = T.generation_bound(q, primes)
        # subgroup generated by primes < N is proper, by primes <= N is everything
        def span(gens):
            H = {1}
            for g in gens:
                while True:
                    new = {(h * g) % q for h in H} | H
                    if new == H:
                        break
                    H = new
            return H
        below = span([p % q for p in primes if p < N and q % p])
        upto = span([p % q for p in primes if p <= N and q % p])
        assert len(upto) == len(units) and len(below) < len(units)


def test_ablation_exponent_tracks_abscissa():
    from hunts.qrh_nonresidue.verify import least_x_for
    for th, e in ((F(7, 8), 8), (F(15, 16), 16)):
        Ct = E.constants(th, F(1, 4))
        x1 = least_x_for(Ct, 1e3, 1e3 / math.log(2))
        x2 = least_x_for(Ct, 1e4, 1e4 / math.log(2))
        slope = math.log(x2 / x1) / math.log(10)
        assert abs(slope - e) < 0.01 * e


def test_planted_fault_is_refuted_by_records(C):
    """Dropping the zero sum gives a q-free 'bound' near 66; n(48473881) = 67."""
    from hunts.qrh_nonresidue.verify import least_x_for
    x_bad = least_x_for(C, 0.0, 0.0)
    assert 60 < x_bad < 67
    assert T.legendre_nonresidue_int(48473881) == 67
    honest = least_x_for(C, math.log(48473881), 0.0)
    assert honest > 67


def test_sieve_factor_values():
    assert E.sieve_factor([2], 1) == 1
    assert E.sieve_factor([2], 0) == 1
    assert E.best_sieve_factor([2, 3]) == 3
    assert E.sieve_factor([2, 3, 5], 0) is None  # delta = 1 - 1/2 - 1/3 - 1/5 < 0
    assert E.best_sieve_factor([2, 3, 5, 7]) <= 2 ** 4 - 1


def test_sieve_inequality_pointwise():
    """Lemma 7's combinatorial step, exhaustively over all units for small p."""
    for p in (31, 211, 421, 2311):
        qs = T.factor_small(p - 1)
        g = next(a for a in range(2, p) if T.is_primitive_root_int(a, p, qs))
        dlog = {}
        x = 1
        for k in range(p - 1):
            dlog[x] = k
            x = x * g % p
        for j in range(len(qs)):
            core, rest = qs[:j], qs[j:]
            if len(rest) < 1:
                continue
            for a in range(1, p):
                k = dlog[a]
                free = lambda ms: all(k % m for m in ms)  # noqa: E731
                lhs = 1 if free(qs) else 0
                rhs = sum(1 for r in rest if free(core + [r])) - (len(rest) - 1) * (1 if free(core) else 0)
                assert lhs >= rhs


def test_miller_liars_lie_in_proper_subgroup():
    """Lemma 8 for every odd composite n < 1500."""
    for n in range(9, 1500, 2):
        if T._is_probable_prime(n):
            continue
        units = [a for a in range(1, n) if gcd(a, n) == 1]
        liars = [a for a in units if T.is_strong_liar(a, n)]
        d, s = n - 1, 0
        while d % 2 == 0:
            d //= 2
            s += 1
        js = [r for r in range(s) for b in liars if pow(b, (2 ** r) * d, n) == n - 1]
        m = (2 ** max(js)) * d
        H = {a for a in units if pow(a, m, n) in (1, n - 1)}
        if len(T.factor_small(n)) == 1:
            H = {a for a in units if pow(a, n - 1, n) == 1}
        assert set(liars) <= H and len(H) < len(units)


def test_tables_against_bounds_and_python_ints():
    N = 200_000
    isp = T.prime_sieve(N)
    spf = T.spf_sieve(N)
    ps = np.nonzero(isp)[0].astype(np.int64)
    odd = ps[ps > 2]
    nr = T.least_nonresidues(odd, ps[:200])
    assert (nr <= np.log(odd.astype(float)) ** 8).all()
    Fm = T.distinct_prime_factors(odd - 1, spf)
    gs = T.least_primitive_roots(odd, Fm, [int(x) for x in ps[:300]])
    oddn = np.arange(9, N + 1, 2)
    comp = oddn[~isp[oddn]]
    w = T.least_strong_witness(comp)
    assert (w <= np.log(comp.astype(float)) ** 8).all()
    rng = np.random.default_rng(1)
    for i in rng.choice(len(odd), 60, replace=False):
        p = int(odd[i])
        assert T.legendre_nonresidue_int(p) == nr[i]
        assert T.least_primitive_root_int(p, prime_only=True) == gs[i]
        lam = E.best_sieve_factor(T.factor_small(p - 1))
        assert gs[i] <= (float(max(lam, 1)) * math.log(p)) ** 8
    for i in rng.choice(len(comp), 60, replace=False):
        assert T.least_strong_witness_int(int(comp[i])) == w[i]
    assert T.least_strong_witness_int(2047) == 3
    assert T.least_strong_witness_int(1373653) == 5


def test_theorem3_closed_margin(C):
    L = arb(5) / 2
    for lam in (1, 2, 7, 100):
        x = (8 * (arb(lam) * L).log()).exp()
        assert _lo(E.primroot_margin(C, x, L, arb(lam), True)) > 0


def test_recorded_verification_is_consistent():
    path = HERE / "verification.json"
    if not path.exists():
        pytest.skip("verification.json not generated")
    d = json.loads(path.read_text())
    assert d["theorem1"]["margin_positive"] and d["theorem1"]["part_b"]["margin_positive"]
    assert d["theorem3"]["margin_positive"]
    assert d["small_moduli"]["all_within_log8"]
    assert d["tables"]["min_margin_log8_over_n"] > 1
    assert d["lesion"]["refuted_by_A000229_count"] > 0


def _S_zeta(x, c):
    """Direct prime-power sum S(1; x) = sum Lambda(n) (n/x)^c log(x/n)."""
    total = mp.mpf(0)
    for n in range(2, int(x) + 1):
        f = T.factor_small(n)
        if len(f) == 1:
            total += mp.log(f[0]) * (mp.mpf(n) / x) ** c * mp.log(x / n)
    return total


def test_explicit_formula_normalisation_for_zeta(C):
    """Lemma 2 for zeta at x = 100, c = 1/4, with 1000 zeros and the residue at -c.

    Truncation tail is below 0.02; flipping the sign of the residue term
    (a planted convention error) moves the right side by about 5.
    """
    zeros = json.loads((HERE.parents[1] / "data" / "zeros_1000.json").read_text())["zeros"]
    with mp.workdps(25):
        x, c = mp.mpf(100), mp.mpf(1) / 4
        lhs = _S_zeta(x, c)
        zsum = mp.mpf(0)
        for g in zeros:
            rho = mp.mpf(1) / 2 + 1j * mp.mpf(g)
            zsum += 2 * mp.re(x ** rho / (rho + c) ** 2)
        triv = mp.nsum(lambda k: x ** (-2 * k) / (2 * k - c) ** 2, [1, mp.inf])
        z0, z1, z2 = (mp.zeta(-c, derivative=k) for k in range(3))
        Fz, Fz1 = -z1 / z0, -(z2 / z0 - (z1 / z0) ** 2)
        res = x ** (-c) * (Fz1 + Fz * mp.log(x))
        rhs = x / (1 + c) ** 2 - zsum - triv + res
        assert abs(lhs - rhs) < 0.03
        assert abs(lhs - (rhs - 2 * res)) > 1


@pytest.mark.parametrize("q,chi,a", [(4, [0, 1, 0, -1], 1), (5, [0, 1, -1, -1, 1], 0)])
def test_residue_formula_for_characters(q, chi, a):
    """Lemma 5's expression for F(-c) = -L'/L(-c) against mpmath's continuation."""
    with mp.workdps(30):
        c = mp.mpf(1) / 4
        L0 = mp.dirichlet(-c, chi)
        L1 = mp.dirichlet(-c, chi, derivative=1)
        direct = -L1 / L0
        Lp = mp.dirichlet(1 + c, chi, derivative=1) / mp.dirichlet(1 + c, chi)  # real chi
        formula = Lp + mp.log(q / mp.pi) + mp.digamma((a - c) / 2) / 2 + mp.digamma((1 + a + c) / 2) / 2
        assert abs(direct - formula) < mp.mpf(10) ** -20
        C = E.constants(F(7, 8), F(1, 4))
        assert abs(direct) <= mp.log(q) + mp.mpf(float(C.R1.upper()))


def test_quartic_kernel_constant_closed_form():
    """sup over gamma of |W|/Re 1/(sigma0-rho) at beta = theta, W = (s+c)^-4."""
    th, c = 7 / 8, 0.02
    D = th + c
    d = D / math.sqrt(3)
    assert d > 1 / 8  # sigma0 = theta + d > 1, so Lemma 3's bound applies
    g = np.concatenate([np.linspace(0, 10, 200001), np.logspace(1, 5, 2000)])
    ratio = (d * d + g * g) / (d * (D * D + g * g) ** 2)
    assert abs(ratio.max() - 3 * math.sqrt(3) / (8 * D ** 3)) < 1e-8
    # other choices of sigma0 do no better at this c
    for dd in (0.4, 0.5, 0.6, 0.7):
        r2 = (dd * dd + g * g) / (dd * (D * D + g * g) ** 2)
        assert r2.max() >= ratio.max() - 1e-12
    c1, C8 = E.quartic_kernel_c1(F(7, 8), F(0))
    assert abs(float(c1.mid()) - 96 * math.sqrt(3) / 343) < 1e-15
    assert 0.00304 < float(C8.mid()) < 0.00306


def test_theorem1d_eleven_twelfths_alone():
    """Oct 5 Thm 1.1 (Re s > 11/12) gives n(chi) <= (log q)^12 from L = 2 on."""
    Cd = E.constants(F(11, 12), F(1, 4))
    assert _lo(Cd.A_chi + Cd.A_zeta) > 0
    assert (12 * arb(2).log()) >= Cd.L_star
    vals = [_lo(E.margin_closed(Cd, arb(L))) for L in (2, 2.5, 3, 5, 10, 100)]
    assert vals[0] > 0.16 and all(b >= a for a, b in zip(vals, vals[1:]))
